import Foundation

struct EmojifyrRandomPhrases {
    static let en: [String] = [
        "Happy cat",
        "Angry bird",
        "Flying fish",
        "Birthday cake",
        "Rainbow unicorn",
        "Fire dragon",
        "Ocean wave",
        "Roller coaster",
        "Pizza party",
        "Super hero",
        "Haunted house",
        "Treasure map",
        "Chocolate milk",
        "Shooting star",
        "Sunny day",
        "Broken heart",
        "Love letter",
        "Sleeping bear",
        "Dancing robot",
        "Pirate ship",
        "Magic wand",
        "Frozen lake",
        "Golden crown",
        "Thunder storm",
        "Baby penguin",
        "Hot dog",
        "Moon landing",
        "Rocket ship",
        "Palm tree",
        "Snow globe",
        "Bubble bath",
        "Candy cane",
        "Cowboy hat",
        "Crystal ball",
        "Desert island",
        "Electric guitar",
        "Fairy tale",
        "Ghost train",
        "Ice cream",
        "Jungle gym",
        "Karate chop",
        "Lemon drop",
        "Mountain bike",
        "Night owl",
        "Opera singer",
        "Polar bear",
        "Queen bee",
        "Running shoes",
        "Scarecrow dance",
        "Tiger stripes",
        "Under water",
        "Volcano eruption",
        "Water slide",
        "X-ray vision",
        "Yellow submarine",
        "Zombie apocalypse",
        "Apple pie",
        "Beach ball",
        "Cloud nine",
        "Disco ball",
        "Eagle eye",
        "Flower garden",
        "Grizzly bear",
        "Honey bee",
        "Igloo house",
        "Jelly fish",
        "King cobra",
        "Lion king",
        "Monkey bar",
        "Ninja star",
        "Octopus hug",
        "Panda bear",
        "Quiet mouse",
        "Race car",
        "Space shuttle",
        "Teddy bear",
        "Umbrella rain",
        "Viking ship",
        "Whale song",
        "Xmas tree",
        "Yoga pose",
        "Zebra crossing",
        "Cotton candy",
        "Sail boat",
        "Cherry blossom",
        "Puppy love",
        "Starry night",
        "Lazy cat",
        "Wild horse",
        "Deep sea",
        "Full moon",
        "Red rose",
        "Blue whale",
        "Green tea",
        "Black swan",
        "White rabbit",
        "Pink flamingo",
        "Purple rain",
        "Orange juice",
        "Silver bullet",
        "Golden egg",
        "Snowy mountain",
        "Sandy beach",
        "Rainy day",
        "Windy hill",
        "Foggy morning",
        "Icy road",
        "Sunny beach",
        "Stormy sea",
        "Misty forest",
        "Dusty trail",
        "Fire truck",
        "Police car",
        "School bus",
        "Train station",
        "Airport runway",
        "Parking lot",
        "Swimming pool",
        "Tennis court",
        "Soccer field",
        "Baseball diamond",
        "Boxing ring",
        "Bowling alley",
        "Skate park",
        "Surf board",
        "Snow board",
        "Ski jump",
        "Golf club",
        "Fishing rod",
        "Camp fire",
        "Tent city",
        "Tree house",
        "Bird house",
        "Dog park",
        "Cat nap",
        "Fox trot",
        "Swan lake",
        "Frog prince",
        "Mouse trap",
        "Shark attack",
        "Spider web",
        "Ant hill",
        "Bee hive",
        "Crab walk",
        "Dolphin jump",
        "Elephant trunk",
        "Giraffe neck",
        "Hippo yawn",
        "Koala hug",
        "Llama spit",
        "Meerkat watch",
        "Narwhal horn",
        "Owl hoot",
        "Parrot talk",
        "Quail egg",
        "Raccoon mask",
        "Seal clap",
        "Turtle shell",
        "Vulture circle",
        "Walrus tusk",
        "Yak butter",
        "Zip line",
        "Banana split",
        "Corn dog",
        "Donut hole",
        "Egg roll",
        "Fish taco",
        "Grape vine",
        "Ham burger",
        "Ice pop",
        "Jam jar",
        "Kiwi fruit",
        "Lime green",
        "Mango salsa",
        "Nut cracker",
        "Olive branch",
        "Peach cobbler",
        "Rice ball",
        "Sushi roll",
        "Taco truck",
        "Veggie burger",
        "Waffle cone",
        "Candy apple",
        "Gummy bear",
        "Jelly bean",
        "Lollipop stick",
        "Marsh mallow",
        "Popcorn bag",
        "Pretzel twist",
        "Cheese wheel",
        "Bread basket",
        "Butter cup",
        "Cup cake",
        "Pancake stack",
        "French toast",
        "Fried egg",
        "Bacon strip",
        "Coffee cup",
        "Tea pot",
        "Milk shake",
        "Smoothie bowl",
        "Fruit punch",
        "Lemon aid",
        "Soda pop",
        "Root beer",
        "Ginger snap",
        "Cinnamon roll",
        "Pumpkin pie",
        "Carrot cake",
        "Red velvet",
        "Angel food",
        "Devil horn",
        "Witch hat",
        "Wizard staff",
        "Dragon egg",
        "Phoenix wing",
        "Griffin claw",
        "Mermaid tail",
        "Centaur gallop",
        "Fairy dust",
        "Pixie wing",
        "Elf ear",
        "Dwarf axe",
        "Goblin gold",
        "Troll bridge",
        "Giant step",
        "Knight armor",
        "Castle tower",
        "Moat water",
        "Draw bridge",
        "Throne room",
        "Royal feast",
        "Magic mirror",
        "Poison apple",
        "Glass slipper",
        "Pumpkin carriage",
        "Spinning wheel",
        "Enchanted forest",
        "Cursed ring",
        "Hidden cave",
        "Secret passage",
        "Treasure chest",
        "Gold coin",
        "Silver key",
        "Bronze shield",
        "Iron sword",
        "Diamond ring",
        "Ruby slippers",
        "Emerald city",
        "Sapphire sky",
        "Pearl necklace",
        "Coral reef",
        "Lava flow",
        "Crystal cave",
        "Amber stone",
        "Jade garden",
        "Topaz sun",
        "Opal moon",
        "Cloud castle",
        "Sky bridge",
        "Star gate",
        "Sun dial",
        "Moon beam",
        "Comet tail",
        "Meteor shower",
        "Galaxy swirl",
        "Nebula cloud",
        "Black hole",
        "Time machine",
        "Robot army",
        "Laser beam",
        "Force field",
        "Jet pack",
        "Hover board",
        "Warp speed",
        "Alien ship",
        "Space walk",
        "Moon base",
        "Mars rover",
        "Saturn ring",
        "Star dust",
        "Cosmic ray",
        "Solar flare",
        "Northern lights",
        "Southern cross",
        "Trade wind",
        "Tidal wave",
        "Earth quake",
        "Sand storm",
        "Heat wave",
        "Cold snap",
        "Rain cloud",
        "Snow flake",
        "Hail stone",
        "Lightning bolt",
        "Thunder clap",
        "Twister spin",
        "Flood gate",
        "Mud slide",
        "Rock slide",
        "Avalanche rush",
        "Geyser blast",
        "Hot spring",
        "Waterfall drop",
        "River bend",
        "Lake shore",
        "Pond lily",
        "Creek bed",
        "Marsh land",
        "Swamp thing",
        "Jungle vine",
        "Rain forest",
        "Bamboo grove",
        "Willow tree",
        "Oak tree",
        "Pine cone",
        "Maple leaf",
        "Acorn hat",
        "Moss rock",
        "Fern leaf",
        "Cactus flower",
        "Sun flower",
        "Tulip field",
        "Rose garden",
        "Daisy chain",
        "Violet bloom",
        "Orchid stem",
        "Lily pad",
        "Lotus pond",
        "Clover patch",
        "Mushroom cap",
        "Berry bush",
        "Apple tree",
        "Lemon tree",
        "Peach tree",
        "Plum blossom",
        "Fig leaf",
        "Coconut palm",
        "Banana peel",
        "Pineapple top",
        "Strawberry field",
        "Blueberry hill",
        "Raspberry jam",
        "Watermelon slice",
        "Melon ball",
        "Pear drop",
        "Cherry bomb",
        "Olive oil",
        "Corn field",
        "Wheat stalk",
        "Rice paddy",
        "Potato sack",
        "Tomato sauce",
        "Pepper mill",
        "Onion ring",
        "Garlic bread",
        "Herb garden",
        "Spice rack",
        "Salt lake",
        "Sugar cane",
        "Honey pot",
        "Maple syrup",
        "Vanilla bean",
        "Cocoa bean",
        "Coffee bean",
        "Tea leaf",
        "Mint leaf",
        "Basil pot",
        "Paint brush",
        "Color wheel",
        "Sketch pad",
        "Clay pot",
        "Wood carving",
        "Paper crane",
        "Ink blot",
        "Chalk board",
        "Crayon box",
        "Pencil case",
        "Book worm",
        "Page turner",
        "Story book",
        "Comic strip",
        "Music box",
        "Drum roll",
        "Piano key",
        "Violin bow",
        "Trumpet blast",
        "Flute song",
        "Harp string",
        "Bell tower",
        "Wind chime",
        "Door bell",
        "Alarm clock",
        "Sand timer",
        "Pocket watch",
        "Sun glasses",
        "Top hat",
        "Bow tie",
        "Red carpet",
        "Spot light",
        "Stage fright",
        "Curtain call",
        "Standing ovation",
        "Encore performance",
        "Grand finale",
        "Fire work",
        "Confetti shower",
        "Balloon float",
        "Kite flying",
        "Paper plane",
        "Toy train",
        "Doll house",
        "Teddy picnic",
        "Puzzle piece",
        "Board game",
        "Card trick",
        "Dice roll",
        "Chess knight",
        "Crown jewel",
        "Lucky charm",
        "Wish bone",
        "Dream catcher",
        "Wind mill",
        "Light house",
        "Watch tower",
        "Clock tower",
        "Water tower",
        "Radio tower",
        "Ferris wheel",
        "Merry round",
        "Bumper car",
        "Fun house",
        "Cotton machine",
        "Prize booth",
        "Ring toss",
        "Duck pond",
        "Petting zoo",
        "Hay ride",
        "Corn maze",
        "Pumpkin patch",
        "Apple orchard",
        "Berry picking",
        "Flower crown",
        "Leaf pile",
        "Snow angel",
        "Sand castle",
        "Mud pie",
        "Rock tower",
        "Shell collection",
        "Drift wood",
        "Sea glass",
        "Tide pool",
        "Hermit crab",
        "Star fish",
        "Sea horse",
        "Blow fish",
        "Sword fish",
        "Clown fish",
        "Angel fish",
        "Hammer head",
        "Sting ray",
        "Electric eel",
        "Squid ink",
        "Whale tail",
        "Seal pup",
        "Otter slide",
        "Penguin waddle",
        "Pelican dive",
        "Seagull cry",
        "Albatross glide",
        "Peacock strut",
        "Flamingo stand",
        "Heron fish",
        "Robin song",
        "Sparrow hop",
        "Cardinal red",
        "Blue jay",
        "Humming bird",
        "Wood pecker",
        "Bald eagle",
        "Hawk eye",
        "Falcon dive",
        "Dove peace",
        "Campfire song",
        "Candy store",
        "Crescent moon",
        "Dancing flame",
        "Falling leaf",
        "Garden gnome",
        "Glowing lantern",
        "Horseshoe luck",
        "Laughing hyena",
        "Magic carpet",
        "Morning dew",
        "Noodle soup",
        "Sleepy sloth",
        "Starfish beach",
        "Sunset glow",
        "Tropical bird",
        "Warm blanket",
    ]

    static let ja: [String] = [
        "幸せな猫",
        "怒った鳥",
        "飛ぶ魚",
        "誕生日ケーキ",
        "虹のユニコーン",
        "火の竜",
        "海の波",
        "ジェットコースター",
        "ピザパーティー",
        "スーパーヒーロー",
        "お化け屋敷",
        "宝の地図",
        "チョコレートミルク",
        "流れ星",
        "晴れた日",
        "失恋の心",
        "ラブレター",
        "眠るクマ",
        "踊るロボット",
        "海賊船",
        "魔法の杖",
        "凍った湖",
        "金の王冠",
        "雷の嵐",
        "赤ちゃんペンギン",
        "ホットドッグ",
        "月面着陸",
        "ロケット船",
        "ヤシの木",
        "スノードーム",
        "泡のお風呂",
        "キャンディーケーン",
        "カウボーイハット",
        "水晶玉",
        "無人島",
        "エレキギター",
        "おとぎ話",
        "お化け電車",
        "アイスクリーム",
        "ジャングルジム",
        "空手チョップ",
        "レモンドロップ",
        "マウンテンバイク",
        "夜のフクロウ",
        "オペラ歌手",
        "白クマ",
        "女王バチ",
        "ランニングシューズ",
        "かかしの踊り",
        "虎の縞模様",
        "水の中",
        "火山の噴火",
        "ウォータースライダー",
        "透視能力",
        "黄色い潜水艦",
        "ゾンビの黙示録",
        "アップルパイ",
        "ビーチボール",
        "天にも昇る気持ち",
        "ミラーボール",
        "鷹の目",
        "花の庭",
        "グリズリーベア",
        "ミツバチ",
        "かまくら",
        "クラゲ",
        "キングコブラ",
        "百獣の王",
        "うんてい遊び",
        "忍者の手裏剣",
        "タコの抱擁",
        "パンダ",
        "静かなネズミ",
        "レースカー",
        "スペースシャトル",
        "テディベア",
        "雨の傘",
        "バイキング船",
        "クジラの歌",
        "クリスマスツリー",
        "ヨガのポーズ",
        "横断歩道",
        "綿あめ",
        "ヨット",
        "桜の花",
        "子犬の愛",
        "星空の夜",
        "のんびり猫",
        "野生の馬",
        "深い海",
        "満月",
        "赤いバラ",
        "シロナガスクジラ",
        "緑茶",
        "黒い白鳥",
        "白いウサギ",
        "ピンクのフラミンゴ",
        "紫の雨",
        "オレンジジュース",
        "銀の弾丸",
        "金の卵",
        "雪の山",
        "砂浜",
        "雨の日",
        "風の丘",
        "霧の朝",
        "凍った道",
        "晴れたビーチ",
        "荒れた海",
        "霧の森",
        "砂ぼこりの道",
        "消防車",
        "パトカー",
        "スクールバス",
        "駅のホーム",
        "空港の滑走路",
        "駐車場",
        "プール",
        "テニスコート",
        "サッカー場",
        "野球のダイヤモンド",
        "ボクシングリング",
        "ボウリング場",
        "スケートパーク",
        "サーフボード",
        "スノーボード",
        "スキージャンプ",
        "ゴルフクラブ",
        "釣り竿",
        "キャンプファイヤー",
        "テント村",
        "ツリーハウス",
        "巣箱",
        "ドッグラン",
        "猫のうたた寝",
        "フォックストロット",
        "白鳥の湖",
        "カエルの王子",
        "ネズミ捕り",
        "サメの襲撃",
        "蜘蛛の巣",
        "アリの巣",
        "蜂の巣",
        "カニ歩き",
        "イルカのジャンプ",
        "ゾウの鼻",
        "キリンの首",
        "カバのあくび",
        "コアラのハグ",
        "ラマの唾",
        "ミーアキャットの見張り",
        "イッカクの角",
        "フクロウの鳴き声",
        "オウムのおしゃべり",
        "ウズラの卵",
        "アライグマの仮面",
        "アシカの拍手",
        "カメの甲羅",
        "ハゲタカの旋回",
        "セイウチの牙",
        "ヤクのバター",
        "ジップライン",
        "バナナスプリット",
        "コーンドッグ",
        "ドーナツの穴",
        "春巻き",
        "フィッシュタコス",
        "ブドウの蔓",
        "ハンバーガー",
        "アイスキャンディー",
        "ジャムの瓶",
        "キウイフルーツ",
        "ライムグリーン",
        "マンゴーサルサ",
        "くるみ割り人形",
        "オリーブの枝",
        "ピーチコブラー",
        "おにぎり",
        "巻き寿司",
        "タコスの屋台",
        "ベジバーガー",
        "ワッフルコーン",
        "りんご飴",
        "グミベア",
        "ジェリービーンズ",
        "ペロペロキャンディー",
        "マシュマロ",
        "ポップコーンの袋",
        "プレッツェル",
        "チーズの丸",
        "パンのかご",
        "バターカップ",
        "カップケーキ",
        "パンケーキの山",
        "フレンチトースト",
        "目玉焼き",
        "ベーコン",
        "コーヒーカップ",
        "急須",
        "ミルクセーキ",
        "スムージーボウル",
        "フルーツパンチ",
        "レモネード",
        "炭酸ジュース",
        "ルートビア",
        "ジンジャースナップ",
        "シナモンロール",
        "パンプキンパイ",
        "キャロットケーキ",
        "レッドベルベット",
        "エンジェルケーキ",
        "悪魔の角",
        "魔女の帽子",
        "魔法使いの杖",
        "竜の卵",
        "不死鳥の翼",
        "グリフォンの爪",
        "人魚のしっぽ",
        "ケンタウロスの疾走",
        "妖精の粉",
        "ピクシーの羽",
        "エルフの耳",
        "ドワーフの斧",
        "ゴブリンの金",
        "トロルの橋",
        "巨人の一歩",
        "騎士の鎧",
        "城の塔",
        "お堀の水",
        "跳ね橋",
        "玉座の間",
        "王室の宴",
        "魔法の鏡",
        "毒リンゴ",
        "ガラスの靴",
        "カボチャの馬車",
        "紡ぎ車",
        "魔法の森",
        "呪いの指輪",
        "隠れた洞窟",
        "秘密の通路",
        "宝箱",
        "金貨",
        "銀の鍵",
        "青銅の盾",
        "鉄の剣",
        "ダイヤの指輪",
        "ルビーの靴",
        "エメラルドの都",
        "サファイアの空",
        "真珠のネックレス",
        "サンゴ礁",
        "溶岩の流れ",
        "水晶の洞窟",
        "琥珀の石",
        "翡翠の庭",
        "トパーズの太陽",
        "オパールの月",
        "雲の城",
        "空の橋",
        "星の門",
        "日時計",
        "月の光",
        "彗星のしっぽ",
        "流星群",
        "銀河の渦",
        "星雲の雲",
        "ブラックホール",
        "タイムマシン",
        "ロボット軍団",
        "レーザービーム",
        "バリアフィールド",
        "ジェットパック",
        "ホバーボード",
        "ワープ速度",
        "宇宙人の船",
        "宇宙遊泳",
        "月面基地",
        "火星探査車",
        "土星の輪",
        "星のかけら",
        "宇宙線",
        "太陽フレア",
        "オーロラ",
        "南十字星",
        "貿易風",
        "津波",
        "地震",
        "砂嵐",
        "熱波",
        "寒波",
        "雨雲",
        "雪の結晶",
        "あられ",
        "稲妻",
        "雷鳴",
        "竜巻の回転",
        "水門",
        "地滑り",
        "落石",
        "雪崩",
        "間欠泉の噴出",
        "温泉",
        "滝の落下",
        "川の曲がり",
        "湖の岸",
        "池の蓮",
        "小川の底",
        "湿地帯",
        "沼の怪物",
        "ジャングルの蔓",
        "熱帯雨林",
        "竹林",
        "柳の木",
        "樫の木",
        "松ぼっくり",
        "紅葉の葉",
        "どんぐりの帽子",
        "苔むした岩",
        "シダの葉",
        "サボテンの花",
        "ひまわり",
        "チューリップ畑",
        "バラの庭",
        "デイジーの花輪",
        "すみれの花",
        "蘭の茎",
        "蓮の葉",
        "蓮の池",
        "クローバーの丘",
        "キノコの傘",
        "ベリーの茂み",
        "リンゴの木",
        "レモンの木",
        "桃の木",
        "梅の花",
        "いちじくの葉",
        "ココナッツヤシ",
        "バナナの皮",
        "パイナップルの頭",
        "いちご畑",
        "ブルーベリーの丘",
        "ラズベリージャム",
        "スイカの一切れ",
        "メロンボール",
        "洋梨のしずく",
        "さくらんぼ爆弾",
        "オリーブオイル",
        "とうもろこし畑",
        "小麦の穂",
        "田んぼ",
        "ジャガイモの袋",
        "トマトソース",
        "コショウ挽き",
        "オニオンリング",
        "ガーリックトースト",
        "ハーブガーデン",
        "スパイスラック",
        "塩の湖",
        "サトウキビ",
        "蜂蜜の壺",
        "メープルシロップ",
        "バニラビーンズ",
        "カカオ豆",
        "コーヒー豆",
        "茶葉",
        "ミントの葉",
        "バジルの鉢",
        "絵筆",
        "色相環",
        "スケッチブック",
        "陶器の壺",
        "木彫り",
        "折り鶴",
        "墨のしみ",
        "黒板",
        "クレヨンの箱",
        "筆箱",
        "本の虫",
        "ページめくり",
        "絵本",
        "漫画",
        "オルゴール",
        "ドラムロール",
        "ピアノの鍵盤",
        "バイオリンの弓",
        "トランペットの音",
        "フルートの歌",
        "ハープの弦",
        "鐘楼",
        "風鈴",
        "玄関のベル",
        "目覚まし時計",
        "砂時計",
        "懐中時計",
        "サングラス",
        "シルクハット",
        "蝶ネクタイ",
        "レッドカーペット",
        "スポットライト",
        "舞台恐怖",
        "カーテンコール",
        "スタンディングオベーション",
        "アンコール公演",
        "グランドフィナーレ",
        "花火",
        "紙吹雪の雨",
        "風船の旅",
        "凧揚げ",
        "紙飛行機",
        "おもちゃの列車",
        "ドールハウス",
        "テディベアのピクニック",
        "パズルのピース",
        "ボードゲーム",
        "カードマジック",
        "サイコロの目",
        "チェスのナイト",
        "王冠の宝石",
        "幸運のお守り",
        "願い骨",
        "ドリームキャッチャー",
        "風車",
        "灯台",
        "見張りの塔",
        "時計台",
        "給水塔",
        "電波塔",
        "観覧車",
        "メリーゴーラウンド",
        "バンパーカー",
        "お化け屋敷",
        "わたあめ機",
        "景品コーナー",
        "輪投げ",
        "アヒルの池",
        "ふれあい動物園",
        "干し草の馬車",
        "トウモロコシ迷路",
        "カボチャ畑",
        "リンゴ園",
        "ベリー狩り",
        "花の冠",
        "落ち葉の山",
        "雪の天使",
        "砂の城",
        "泥だんご",
        "石の塔",
        "貝殻集め",
        "流木",
        "シーグラス",
        "潮だまり",
        "ヤドカリ",
        "ヒトデ",
        "タツノオトシゴ",
        "フグ",
        "メカジキ",
        "クマノミ",
        "エンゼルフィッシュ",
        "シュモクザメ",
        "アカエイ",
        "デンキウナギ",
        "イカスミ",
        "クジラの尻尾",
        "アザラシの子",
        "カワウソの滑り台",
        "ペンギンの行進",
        "ペリカンの急降下",
        "カモメの鳴き声",
        "アホウドリの滑空",
        "孔雀の歩き",
        "フラミンゴ立ち",
        "サギの魚獲り",
        "コマドリの歌",
        "スズメの跳び",
        "赤い鶴",
        "カケスの青",
        "ハチドリ",
        "キツツキ",
        "ハクトウワシ",
        "鷹の眼",
        "ハヤブサの急降下",
        "平和のハト",
        "焚き火の歌",
        "お菓子屋さん",
        "三日月",
        "踊る炎",
        "落ちる葉",
        "庭の小人",
        "光るランタン",
        "蹄鉄の幸運",
        "笑うハイエナ",
        "魔法のじゅうたん",
        "朝の露",
        "麺のスープ",
        "眠いナマケモノ",
        "ヒトデの浜辺",
        "夕焼けの輝き",
        "南国の鳥",
        "暖かい毛布",
    ]

    static func random(lang: String) -> String {
        let list = lang == "ja" ? ja : en
        return list.randomElement() ?? list[0]
    }
}
