// Internet initialisms with bilingual definitions
export const INITIALISMS: Array<{ text: string; defEn: string; defJa: string }> = [
  { text: "LOL", defEn: "Laughing Out Loud", defJa: "大笑い（声を出して笑う）" },
  { text: "LMAO", defEn: "Laughing My A** Off", defJa: "爆笑（めちゃくちゃ笑う）" },
  { text: "BRB", defEn: "Be Right Back", defJa: "すぐ戻る" },
  { text: "OMG", defEn: "Oh My God", defJa: "なんてこった" },
  { text: "ROFL", defEn: "Rolling On the Floor Laughing", defJa: "床を転がって笑う" },
  { text: "SMH", defEn: "Shaking My Head", defJa: "あきれて首を振る" },
  { text: "IDK", defEn: "I Don't Know", defJa: "知らない・わからない" },
  { text: "TBH", defEn: "To Be Honest", defJa: "正直に言うと" },
  { text: "IMO", defEn: "In My Opinion", defJa: "私の意見では" },
  { text: "FOMO", defEn: "Fear Of Missing Out", defJa: "取り残される不安" },
  { text: "YOLO", defEn: "You Only Live Once", defJa: "人生は一度きり" },
  { text: "FTW", defEn: "For The Win", defJa: "最高！勝利のために" },
  { text: "GOAT", defEn: "Greatest Of All Time", defJa: "史上最高" },
  { text: "ICYMI", defEn: "In Case You Missed It", defJa: "見逃した方のために" },
  { text: "TL;DR", defEn: "Too Long; Didn't Read", defJa: "長すぎて読まなかった（要約）" },
  { text: "AFK", defEn: "Away From Keyboard", defJa: "席を外してます" },
  { text: "GG", defEn: "Good Game", defJa: "いい試合だった" },
  { text: "IRL", defEn: "In Real Life", defJa: "現実では・リアルで" },
  { text: "NVM", defEn: "Never Mind", defJa: "気にしないで" },
  { text: "TGIF", defEn: "Thank God It's Friday", defJa: "やっと金曜日だ！" },
  { text: "FYI", defEn: "For Your Information", defJa: "参考までに" },
  { text: "BTW", defEn: "By The Way", defJa: "ところで" },
  { text: "DM", defEn: "Direct Message", defJa: "ダイレクトメッセージ" },
  { text: "ASAP", defEn: "As Soon As Possible", defJa: "できるだけ早く" },
  { text: "TMI", defEn: "Too Much Information", defJa: "情報多すぎ" },
  { text: "TTYL", defEn: "Talk To You Later", defJa: "またあとでね" },
  { text: "IYKYK", defEn: "If You Know You Know", defJa: "わかる人にはわかる" },
  { text: "NGL", defEn: "Not Gonna Lie", defJa: "嘘じゃなく・正直" },
  { text: "OOTD", defEn: "Outfit Of The Day", defJa: "今日のコーデ" },
  { text: "NSFW", defEn: "Not Safe For Work", defJa: "職場閲覧注意" },
  { text: "FWIW", defEn: "For What It's Worth", defJa: "一応言っておくと" },
  { text: "IIRC", defEn: "If I Remember Correctly", defJa: "確か…だったと思う" },
  { text: "WFH", defEn: "Work From Home", defJa: "在宅勤務" },
  { text: "EOD", defEn: "End Of Day", defJa: "今日中に" },
  { text: "ETA", defEn: "Estimated Time of Arrival", defJa: "到着予定時間" },
  { text: "RSVP", defEn: "Please Reply (Répondez S'il Vous Plaît)", defJa: "出欠のご返信をお願いします" },
  { text: "TBA", defEn: "To Be Announced", defJa: "後日発表" },
  { text: "DIY", defEn: "Do It Yourself", defJa: "自分でやる・手作り" },
  { text: "MVP", defEn: "Most Valuable Player", defJa: "最優秀選手" },
  { text: "BOGO", defEn: "Buy One Get One", defJa: "1つ買うと1つ無料" },
  // 41–80
  { text: "IMHO", defEn: "In My Humble Opinion", defJa: "私の拙い意見では" },
  { text: "AFAIK", defEn: "As Far As I Know", defJa: "私の知る限り" },
  { text: "TIL", defEn: "Today I Learned", defJa: "今日知ったこと" },
  { text: "LMFAO", defEn: "Laughing My F***ing A** Off", defJa: "超爆笑" },
  { text: "STFU", defEn: "Shut The F*** Up", defJa: "黙れ" },
  { text: "GTFO", defEn: "Get The F*** Out", defJa: "出て行け" },
  { text: "WTF", defEn: "What The F***", defJa: "何だこれ" },
  { text: "DGAF", defEn: "Don't Give A F***", defJa: "全く気にしない" },
  { text: "NBD", defEn: "No Big Deal", defJa: "大したことない" },
  { text: "IDGAF", defEn: "I Don't Give A F***", defJa: "全く気にしない" },
  { text: "JK", defEn: "Just Kidding", defJa: "冗談だよ" },
  { text: "OG", defEn: "Original Gangster / Original", defJa: "元祖・オリジナル" },
  { text: "SNAFU", defEn: "Situation Normal, All F***ed Up", defJa: "いつも通りの混乱" },
  { text: "FUBAR", defEn: "F***ed Up Beyond All Repair", defJa: "修復不可能にめちゃくちゃ" },
  { text: "FWIW", defEn: "For What It's Worth", defJa: "一応言っておくと" },
  { text: "HMU", defEn: "Hit Me Up", defJa: "連絡して" },
  { text: "LMK", defEn: "Let Me Know", defJa: "教えてね" },
  { text: "IIUC", defEn: "If I Understand Correctly", defJa: "正しく理解していれば" },
  { text: "TFW", defEn: "That Feeling When", defJa: "〜な時の気持ち" },
  { text: "MFW", defEn: "My Face When", defJa: "〜な時の私の顔" },
  { text: "MRW", defEn: "My Reaction When", defJa: "〜な時の私のリアクション" },
  { text: "SMH", defEn: "Shaking My Head", defJa: "あきれて首を振る" },
  { text: "IIRC", defEn: "If I Recall Correctly", defJa: "確か…だったと思う" },
  { text: "TBD", defEn: "To Be Determined", defJa: "未定" },
  { text: "TBC", defEn: "To Be Confirmed", defJa: "確認中" },
  { text: "OOO", defEn: "Out Of Office", defJa: "不在中" },
  { text: "PTO", defEn: "Paid Time Off", defJa: "有給休暇" },
  { text: "TLDR", defEn: "Too Long Didn't Read", defJa: "長すぎて読まなかった" },
  { text: "WDYM", defEn: "What Do You Mean", defJa: "どういう意味？" },
  { text: "NP", defEn: "No Problem", defJa: "問題ないよ" },
  // 81–120
  { text: "OFC", defEn: "Of Course", defJa: "もちろん" },
  { text: "ISTG", defEn: "I Swear To God", defJa: "マジで誓う" },
  { text: "SMDH", defEn: "Shaking My Damn Head", defJa: "まじであきれる" },
  { text: "RN", defEn: "Right Now", defJa: "今すぐ" },
  { text: "ATM", defEn: "At The Moment", defJa: "今のところ" },
  { text: "IGHT", defEn: "Alright", defJa: "了解・オッケー" },
  { text: "BET", defEn: "Agreed / For Sure", defJa: "了解・間違いない" },
  { text: "IGHT", defEn: "Alright", defJa: "オッケー" },
  { text: "SLAY", defEn: "To Do Something Exceptionally Well", defJa: "最高にキメてる" },
  { text: "PERIODT", defEn: "Period (emphatic, end of discussion)", defJa: "以上（強調・議論の終わり）" },
  { text: "FR", defEn: "For Real", defJa: "マジで" },
  { text: "NPC", defEn: "Non-Player Character (boring person)", defJa: "モブキャラ（つまらない人）" },
  { text: "MID", defEn: "Average / Mediocre", defJa: "普通・微妙" },
  { text: "BUSSIN", defEn: "Really Good (especially food)", defJa: "めちゃうまい（特に食べ物）" },
  { text: "CEO", defEn: "Chief Executive Officer (best at something)", defJa: "〜の達人・王者" },
  { text: "GOATED", defEn: "Being The Greatest Of All Time", defJa: "史上最高にイケてる" },
  { text: "BASED", defEn: "Unapologetically Oneself", defJa: "自分を貫いてる・カッコいい" },
  { text: "CRINGE", defEn: "Embarrassingly Awkward", defJa: "痛い・恥ずかしい" },
  { text: "SUS", defEn: "Suspicious", defJa: "怪しい" },
  { text: "CAP", defEn: "Lie / Falsehood", defJa: "嘘" },
  { text: "NO CAP", defEn: "No Lie / For Real", defJa: "嘘じゃない・マジ" },
  { text: "STAN", defEn: "Super Fan / Obsessive Supporter", defJa: "熱狂的ファン" },
  { text: "SIMP", defEn: "Someone Overly Devoted To Another", defJa: "貢ぐ人・べた惚れ" },
  { text: "W", defEn: "Win", defJa: "勝ち" },
  { text: "L", defEn: "Loss / Failure", defJa: "負け・失敗" },
  { text: "FLEX", defEn: "Show Off", defJa: "見せびらかす・自慢" },
  { text: "VIBE", defEn: "Mood / Atmosphere", defJa: "雰囲気・ノリ" },
  { text: "FIRE", defEn: "Awesome / Amazing", defJa: "最高・イケてる" },
  { text: "LIT", defEn: "Exciting / Amazing", defJa: "盛り上がってる・最高" },
  { text: "SAVAGE", defEn: "Boldly Ruthless / Fierce", defJa: "容赦ない・ヤバい" },
  // 121–160
  { text: "WOKE", defEn: "Socially Aware / Conscious", defJa: "社会意識が高い" },
  { text: "SALTY", defEn: "Bitter / Upset", defJa: "根に持ってる・イラついてる" },
  { text: "SHADE", defEn: "Subtle Disrespect / Insult", defJa: "さりげない嫌味" },
  { text: "TEA", defEn: "Gossip / Drama", defJa: "ゴシップ・ネタ" },
  { text: "RECEIPTS", defEn: "Proof / Evidence", defJa: "証拠" },
  { text: "CLOUT", defEn: "Influence / Fame", defJa: "影響力・知名度" },
  { text: "FINSTA", defEn: "Fake Instagram (private account)", defJa: "裏アカ（プライベート用）" },
  { text: "DOOMSCROLL", defEn: "Endlessly Scrolling Bad News", defJa: "悪いニュースを延々とスクロール" },
  { text: "GHOSTING", defEn: "Suddenly Cutting Off Contact", defJa: "突然連絡を絶つこと" },
  { text: "BINGE", defEn: "Watch/Do Excessively In One Sitting", defJa: "一気見・一気にやる" },
  { text: "IKR", defEn: "I Know Right", defJa: "だよね！" },
  { text: "SMOL", defEn: "Small And Cute", defJa: "小さくてかわいい" },
  { text: "CHONK", defEn: "Adorably Fat (usually animals)", defJa: "ぽっちゃりでかわいい（主に動物）" },
  { text: "BOOP", defEn: "Gentle Tap (usually on nose)", defJa: "ちょん（鼻を軽くタッチ）" },
  { text: "YEET", defEn: "To Throw With Force", defJa: "力いっぱい投げる" },
  { text: "SKRT", defEn: "Sound Of Tires Screeching / Leaving Fast", defJa: "タイヤの音・急いで去る" },
  { text: "BRUH", defEn: "Bro (expression of disbelief)", defJa: "おい（呆れ・驚き）" },
  { text: "FAM", defEn: "Family / Close Friends", defJa: "仲間・家族同然の友達" },
  { text: "GUCCI", defEn: "Good / Cool / Fine", defJa: "いい感じ・オッケー" },
  { text: "LOWKEY", defEn: "Somewhat / Secretly", defJa: "実はちょっと・こっそり" },
  { text: "HIGHKEY", defEn: "Very Much / Openly", defJa: "めっちゃ・堂々と" },
  { text: "EXTRA", defEn: "Over The Top / Dramatic", defJa: "大げさ・やりすぎ" },
  { text: "BASIC", defEn: "Mainstream / Unoriginal", defJa: "ありきたり・普通すぎ" },
  { text: "MOOD", defEn: "Relatable Feeling", defJa: "わかる・共感" },
  { text: "BIG MOOD", defEn: "Extremely Relatable", defJa: "めっちゃわかる" },
  { text: "SHIP", defEn: "Support A Romantic Pairing", defJa: "カップリングを推す" },
  { text: "OTP", defEn: "One True Pairing", defJa: "最推しカプ" },
  { text: "CANON", defEn: "Officially Part Of The Story", defJa: "公式設定" },
  { text: "FANON", defEn: "Fan-Created Storyline", defJa: "ファンの二次設定" },
  { text: "AU", defEn: "Alternate Universe", defJa: "パラレルワールド・別世界線" },
  // 161–200
  { text: "OC", defEn: "Original Character / Original Content", defJa: "オリジナルキャラ・オリジナルコンテンツ" },
  { text: "OP", defEn: "Original Poster / Overpowered", defJa: "投稿主・強すぎ" },
  { text: "COPIUM", defEn: "Coping Mechanism (ironic)", defJa: "精神安定剤（皮肉）" },
  { text: "HOPIUM", defEn: "Unrealistic Hope (ironic)", defJa: "非現実的な希望（皮肉）" },
  { text: "POGGERS", defEn: "Exciting / Amazing (gaming)", defJa: "すごい・興奮（ゲーム用語）" },
  { text: "KEKW", defEn: "Laughing Hard (Twitch emote)", defJa: "大爆笑（Twitch用語）" },
  { text: "GGWP", defEn: "Good Game Well Played", defJa: "お疲れ様・いい試合" },
  { text: "GGEZ", defEn: "Good Game Easy (taunting)", defJa: "楽勝だった（煽り）" },
  { text: "AMA", defEn: "Ask Me Anything", defJa: "何でも聞いて" },
  { text: "ELI5", defEn: "Explain Like I'm 5", defJa: "5歳にもわかるように説明して" },
  { text: "FTFY", defEn: "Fixed That For You", defJa: "直しておいたよ" },
  { text: "ITT", defEn: "In This Thread", defJa: "このスレでは" },
  { text: "DAE", defEn: "Does Anyone Else", defJa: "他にもこういう人いる？" },
  { text: "IANAL", defEn: "I Am Not A Lawyer", defJa: "私は弁護士じゃないけど" },
  { text: "TLDR", defEn: "Too Long Didn't Read", defJa: "長すぎ（要約）" },
  { text: "PSA", defEn: "Public Service Announcement", defJa: "公共のお知らせ・みんなに伝えたいこと" },
  { text: "HIFW", defEn: "How I Feel When", defJa: "〜の時の気持ち" },
  { text: "YKWIM", defEn: "You Know What I Mean", defJa: "わかるでしょ" },
  { text: "WYWH", defEn: "Wish You Were Here", defJa: "あなたがここにいたらなぁ" },
  { text: "GLHF", defEn: "Good Luck Have Fun", defJa: "頑張って楽しんで" },
  { text: "BFF", defEn: "Best Friends Forever", defJa: "永遠の親友" },
  { text: "BAE", defEn: "Before Anyone Else (partner)", defJa: "一番大事な人・恋人" },
  { text: "MCM", defEn: "Man Crush Monday", defJa: "月曜のイケメン紹介" },
  { text: "WCW", defEn: "Woman Crush Wednesday", defJa: "水曜の美女紹介" },
  { text: "TBT", defEn: "Throwback Thursday", defJa: "木曜の懐かし写真" },
  { text: "OOTW", defEn: "Outfit Of The Week", defJa: "今週のコーデ" },
  { text: "GRWM", defEn: "Get Ready With Me", defJa: "一緒に準備しよう" },
  { text: "ASMR", defEn: "Autonomous Sensory Meridian Response", defJa: "心地よい音の刺激" },
  { text: "POV", defEn: "Point Of View", defJa: "〜の視点" },
  { text: "CEO", defEn: "Chief Executive Officer", defJa: "最高経営責任者" },
  { text: "TLDR", defEn: "Too Long Didn't Read", defJa: "要約" },
  { text: "IMHO", defEn: "In My Humble Opinion", defJa: "個人的な意見では" },
  { text: "ROTFL", defEn: "Rolling On The Floor Laughing", defJa: "床を転げ回って笑う" },
  { text: "ICYDK", defEn: "In Case You Didn't Know", defJa: "知らなかったかもだけど" },
  { text: "JSYK", defEn: "Just So You Know", defJa: "一応知らせておくと" },
  { text: "ILYSM", defEn: "I Love You So Much", defJa: "大好きだよ" },
  { text: "ILY", defEn: "I Love You", defJa: "愛してる" },
  { text: "ISO", defEn: "In Search Of", defJa: "〜を探しています" },
  { text: "LGTM", defEn: "Looks Good To Me", defJa: "良さそう・問題なし" },
  { text: "PITA", defEn: "Pain In The A**", defJa: "面倒くさいやつ" },
  { text: "WDYT", defEn: "What Do You Think", defJa: "どう思う？" },
  { text: "YMMV", defEn: "Your Mileage May Vary", defJa: "人によって違うかも" },
  { text: "SOML", defEn: "Story Of My Life", defJa: "あるある・私の人生そのもの" },
  { text: "FTFY", defEn: "Fixed That For You", defJa: "修正しておいた" },
  { text: "HTH", defEn: "Hope That Helps", defJa: "参考になれば" },
  { text: "CYA", defEn: "See Ya / Cover Your A**", defJa: "じゃあね" },
  { text: "G2G", defEn: "Got To Go", defJa: "もう行かなきゃ" },
  { text: "B4N", defEn: "Bye For Now", defJa: "じゃあまたね" },
  { text: "TTFN", defEn: "Ta Ta For Now", defJa: "それじゃまたね" },
  { text: "XOXO", defEn: "Hugs And Kisses", defJa: "ハグとキス" },
];

export const RANDOM_PHRASES_EN: string[] = [
  "Happy cat",
  "Angry bird",
  "Flying fish",
  "Birthday cake",
  "Rainbow unicorn",
  "Fire dragon",
  "Ocean wave",
  "Roller coaster",
  "Pizza party",
  "Super hero",
  "Haunted house",
  "Treasure map",
  "Chocolate milk",
  "Shooting star",
  "Sunny day",
  "Broken heart",
  "Love letter",
  "Sleeping bear",
  "Dancing robot",
  "Pirate ship",
  "Magic wand",
  "Frozen lake",
  "Golden crown",
  "Thunder storm",
  "Baby penguin",
  "Hot dog",
  "Moon landing",
  "Rocket ship",
  "Palm tree",
  "Snow globe",
  "Bubble bath",
  "Candy cane",
  "Cowboy hat",
  "Crystal ball",
  "Desert island",
  "Electric guitar",
  "Fairy tale",
  "Ghost train",
  "Ice cream",
  "Jungle gym",
  "Karate chop",
  "Lemon drop",
  "Mountain bike",
  "Night owl",
  "Opera singer",
  "Polar bear",
  "Queen bee",
  "Running shoes",
  "Scarecrow dance",
  "Tiger stripes",
  "Under water",
  "Volcano eruption",
  "Water slide",
  "X-ray vision",
  "Yellow submarine",
  "Zombie apocalypse",
  "Apple pie",
  "Beach ball",
  "Cloud nine",
  "Disco ball",
  "Eagle eye",
  "Flower garden",
  "Grizzly bear",
  "Honey bee",
  "Igloo house",
  "Jelly fish",
  "King cobra",
  "Lion king",
  "Monkey bar",
  "Ninja star",
  "Octopus hug",
  "Panda bear",
  "Quiet mouse",
  "Race car",
  "Space shuttle",
  "Teddy bear",
  "Umbrella rain",
  "Viking ship",
  "Whale song",
  "Xmas tree",
  "Yoga pose",
  "Zebra crossing",
  "Cotton candy",
  "Sail boat",
  "Cherry blossom",
  "Puppy love",
  "Starry night",
  "Lazy cat",
  "Wild horse",
  "Deep sea",
  "Full moon",
  "Red rose",
  "Blue whale",
  "Green tea",
  "Black swan",
  "White rabbit",
  "Pink flamingo",
  "Purple rain",
  "Orange juice",
  "Silver bullet",
  "Golden egg",
  "Snowy mountain",
  "Sandy beach",
  "Rainy day",
  "Windy hill",
  "Foggy morning",
  "Icy road",
  "Sunny beach",
  "Stormy sea",
  "Misty forest",
  "Dusty trail",
  "Fire truck",
  "Police car",
  "School bus",
  "Train station",
  "Airport runway",
  "Parking lot",
  "Swimming pool",
  "Tennis court",
  "Soccer field",
  "Baseball diamond",
  "Boxing ring",
  "Bowling alley",
  "Skate park",
  "Surf board",
  "Snow board",
  "Ski jump",
  "Golf club",
  "Fishing rod",
  "Camp fire",
  "Tent city",
  "Tree house",
  "Bird house",
  "Dog park",
  "Cat nap",
  "Fox trot",
  "Swan lake",
  "Frog prince",
  "Mouse trap",
  "Shark attack",
  "Spider web",
  "Ant hill",
  "Bee hive",
  "Crab walk",
  "Dolphin jump",
  "Elephant trunk",
  "Giraffe neck",
  "Hippo yawn",
  "Koala hug",
  "Llama spit",
  "Meerkat watch",
  "Narwhal horn",
  "Owl hoot",
  "Parrot talk",
  "Quail egg",
  "Raccoon mask",
  "Seal clap",
  "Turtle shell",
  "Vulture circle",
  "Walrus tusk",
  "Yak butter",
  "Zip line",
  "Banana split",
  "Corn dog",
  "Donut hole",
  "Egg roll",
  "Fish taco",
  "Grape vine",
  "Ham burger",
  "Ice pop",
  "Jam jar",
  "Kiwi fruit",
  "Lime green",
  "Mango salsa",
  "Nut cracker",
  "Olive branch",
  "Peach cobbler",
  "Rice ball",
  "Sushi roll",
  "Taco truck",
  "Veggie burger",
  "Waffle cone",
  "Candy apple",
  "Gummy bear",
  "Jelly bean",
  "Lollipop stick",
  "Marsh mallow",
  "Popcorn bag",
  "Pretzel twist",
  "Cheese wheel",
  "Bread basket",
  "Butter cup",
  "Cup cake",
  "Pancake stack",
  "French toast",
  "Fried egg",
  "Bacon strip",
  "Coffee cup",
  "Tea pot",
  "Milk shake",
  "Smoothie bowl",
  "Fruit punch",
  "Lemon aid",
  "Soda pop",
  "Root beer",
  "Ginger snap",
  "Cinnamon roll",
  "Pumpkin pie",
  "Carrot cake",
  "Red velvet",
  "Angel food",
  "Devil horn",
  "Witch hat",
  "Wizard staff",
  "Dragon egg",
  "Phoenix wing",
  "Griffin claw",
  "Mermaid tail",
  "Centaur gallop",
  "Fairy dust",
  "Pixie wing",
  "Elf ear",
  "Dwarf axe",
  "Goblin gold",
  "Troll bridge",
  "Giant step",
  "Knight armor",
  "Castle tower",
  "Moat water",
  "Draw bridge",
  "Throne room",
  "Royal feast",
  "Magic mirror",
  "Poison apple",
  "Glass slipper",
  "Pumpkin carriage",
  "Spinning wheel",
  "Enchanted forest",
  "Cursed ring",
  "Hidden cave",
  "Secret passage",
  "Treasure chest",
  "Gold coin",
  "Silver key",
  "Bronze shield",
  "Iron sword",
  "Diamond ring",
  "Ruby slippers",
  "Emerald city",
  "Sapphire sky",
  "Pearl necklace",
  "Coral reef",
  "Lava flow",
  "Crystal cave",
  "Amber stone",
  "Jade garden",
  "Topaz sun",
  "Opal moon",
  "Cloud castle",
  "Sky bridge",
  "Star gate",
  "Sun dial",
  "Moon beam",
  "Comet tail",
  "Meteor shower",
  "Galaxy swirl",
  "Nebula cloud",
  "Black hole",
  "Time machine",
  "Robot army",
  "Laser beam",
  "Force field",
  "Jet pack",
  "Hover board",
  "Warp speed",
  "Alien ship",
  "Space walk",
  "Moon base",
  "Mars rover",
  "Saturn ring",
  "Star dust",
  "Cosmic ray",
  "Solar flare",
  "Northern lights",
  "Southern cross",
  "Trade wind",
  "Tidal wave",
  "Earth quake",
  "Sand storm",
  "Heat wave",
  "Cold snap",
  "Rain cloud",
  "Snow flake",
  "Hail stone",
  "Lightning bolt",
  "Thunder clap",
  "Twister spin",
  "Flood gate",
  "Mud slide",
  "Rock slide",
  "Avalanche rush",
  "Geyser blast",
  "Hot spring",
  "Waterfall drop",
  "River bend",
  "Lake shore",
  "Pond lily",
  "Creek bed",
  "Marsh land",
  "Swamp thing",
  "Jungle vine",
  "Rain forest",
  "Bamboo grove",
  "Willow tree",
  "Oak tree",
  "Pine cone",
  "Maple leaf",
  "Acorn hat",
  "Moss rock",
  "Fern leaf",
  "Cactus flower",
  "Sun flower",
  "Tulip field",
  "Rose garden",
  "Daisy chain",
  "Violet bloom",
  "Orchid stem",
  "Lily pad",
  "Lotus pond",
  "Clover patch",
  "Mushroom cap",
  "Berry bush",
  "Apple tree",
  "Lemon tree",
  "Peach tree",
  "Plum blossom",
  "Fig leaf",
  "Coconut palm",
  "Banana peel",
  "Pineapple top",
  "Strawberry field",
  "Blueberry hill",
  "Raspberry jam",
  "Watermelon slice",
  "Melon ball",
  "Pear drop",
  "Cherry bomb",
  "Olive oil",
  "Corn field",
  "Wheat stalk",
  "Rice paddy",
  "Potato sack",
  "Tomato sauce",
  "Pepper mill",
  "Onion ring",
  "Garlic bread",
  "Herb garden",
  "Spice rack",
  "Salt lake",
  "Sugar cane",
  "Honey pot",
  "Maple syrup",
  "Vanilla bean",
  "Cocoa bean",
  "Coffee bean",
  "Tea leaf",
  "Mint leaf",
  "Basil pot",
  "Paint brush",
  "Color wheel",
  "Sketch pad",
  "Clay pot",
  "Wood carving",
  "Paper crane",
  "Ink blot",
  "Chalk board",
  "Crayon box",
  "Pencil case",
  "Book worm",
  "Page turner",
  "Story book",
  "Comic strip",
  "Music box",
  "Drum roll",
  "Piano key",
  "Violin bow",
  "Trumpet blast",
  "Flute song",
  "Harp string",
  "Bell tower",
  "Wind chime",
  "Door bell",
  "Alarm clock",
  "Sand timer",
  "Pocket watch",
  "Sun glasses",
  "Top hat",
  "Bow tie",
  "Red carpet",
  "Spot light",
  "Stage fright",
  "Curtain call",
  "Standing ovation",
  "Encore performance",
  "Grand finale",
  "Fire work",
  "Confetti shower",
  "Balloon float",
  "Kite flying",
  "Paper plane",
  "Toy train",
  "Doll house",
  "Teddy picnic",
  "Puzzle piece",
  "Board game",
  "Card trick",
  "Dice roll",
  "Chess knight",
  "Crown jewel",
  "Lucky charm",
  "Wish bone",
  "Dream catcher",
  "Wind mill",
  "Light house",
  "Watch tower",
  "Clock tower",
  "Water tower",
  "Radio tower",
  "Ferris wheel",
  "Merry round",
  "Bumper car",
  "Fun house",
  "Cotton machine",
  "Prize booth",
  "Ring toss",
  "Duck pond",
  "Petting zoo",
  "Hay ride",
  "Corn maze",
  "Pumpkin patch",
  "Apple orchard",
  "Berry picking",
  "Flower crown",
  "Leaf pile",
  "Snow angel",
  "Sand castle",
  "Mud pie",
  "Rock tower",
  "Shell collection",
  "Drift wood",
  "Sea glass",
  "Tide pool",
  "Hermit crab",
  "Star fish",
  "Sea horse",
  "Blow fish",
  "Sword fish",
  "Clown fish",
  "Angel fish",
  "Hammer head",
  "Sting ray",
  "Electric eel",
  "Squid ink",
  "Whale tail",
  "Seal pup",
  "Otter slide",
  "Penguin waddle",
  "Pelican dive",
  "Seagull cry",
  "Albatross glide",
  "Peacock strut",
  "Flamingo stand",
  "Heron fish",
  "Robin song",
  "Sparrow hop",
  "Cardinal red",
  "Blue jay",
  "Humming bird",
  "Wood pecker",
  "Bald eagle",
  "Hawk eye",
  "Falcon dive",
  "Dove peace",
  "Campfire song",
  "Candy store",
  "Crescent moon",
  "Dancing flame",
  "Falling leaf",
  "Garden gnome",
  "Glowing lantern",
  "Horseshoe luck",
  "Laughing hyena",
  "Magic carpet",
  "Morning dew",
  "Noodle soup",
  "Sleepy sloth",
  "Starfish beach",
  "Sunset glow",
  "Tropical bird",
  "Warm blanket",
];

export const RANDOM_PHRASES_JA: string[] = [
  "幸せな猫",
  "怒った鳥",
  "飛ぶ魚",
  "誕生日ケーキ",
  "虹のユニコーン",
  "火の竜",
  "海の波",
  "ジェットコースター",
  "ピザパーティー",
  "スーパーヒーロー",
  "お化け屋敷",
  "宝の地図",
  "チョコレートミルク",
  "流れ星",
  "晴れた日",
  "失恋の心",
  "ラブレター",
  "眠るクマ",
  "踊るロボット",
  "海賊船",
  "魔法の杖",
  "凍った湖",
  "金の王冠",
  "雷の嵐",
  "赤ちゃんペンギン",
  "ホットドッグ",
  "月面着陸",
  "ロケット船",
  "ヤシの木",
  "スノードーム",
  "泡のお風呂",
  "キャンディーケーン",
  "カウボーイハット",
  "水晶玉",
  "無人島",
  "エレキギター",
  "おとぎ話",
  "お化け電車",
  "アイスクリーム",
  "ジャングルジム",
  "空手チョップ",
  "レモンドロップ",
  "マウンテンバイク",
  "夜のフクロウ",
  "オペラ歌手",
  "白クマ",
  "女王バチ",
  "ランニングシューズ",
  "かかしの踊り",
  "虎の縞模様",
  "水の中",
  "火山の噴火",
  "ウォータースライダー",
  "透視能力",
  "黄色い潜水艦",
  "ゾンビの黙示録",
  "アップルパイ",
  "ビーチボール",
  "天にも昇る気持ち",
  "ミラーボール",
  "鷹の目",
  "花の庭",
  "グリズリーベア",
  "ミツバチ",
  "かまくら",
  "クラゲ",
  "キングコブラ",
  "百獣の王",
  "うんてい遊び",
  "忍者の手裏剣",
  "タコの抱擁",
  "パンダ",
  "静かなネズミ",
  "レースカー",
  "スペースシャトル",
  "テディベア",
  "雨の傘",
  "バイキング船",
  "クジラの歌",
  "クリスマスツリー",
  "ヨガのポーズ",
  "横断歩道",
  "綿あめ",
  "ヨット",
  "桜の花",
  "子犬の愛",
  "星空の夜",
  "のんびり猫",
  "野生の馬",
  "深い海",
  "満月",
  "赤いバラ",
  "シロナガスクジラ",
  "緑茶",
  "黒い白鳥",
  "白いウサギ",
  "ピンクのフラミンゴ",
  "紫の雨",
  "オレンジジュース",
  "銀の弾丸",
  "金の卵",
  "雪の山",
  "砂浜",
  "雨の日",
  "風の丘",
  "霧の朝",
  "凍った道",
  "晴れたビーチ",
  "荒れた海",
  "霧の森",
  "砂ぼこりの道",
  "消防車",
  "パトカー",
  "スクールバス",
  "駅のホーム",
  "空港の滑走路",
  "駐車場",
  "プール",
  "テニスコート",
  "サッカー場",
  "野球のダイヤモンド",
  "ボクシングリング",
  "ボウリング場",
  "スケートパーク",
  "サーフボード",
  "スノーボード",
  "スキージャンプ",
  "ゴルフクラブ",
  "釣り竿",
  "キャンプファイヤー",
  "テント村",
  "ツリーハウス",
  "巣箱",
  "ドッグラン",
  "猫のうたた寝",
  "フォックストロット",
  "白鳥の湖",
  "カエルの王子",
  "ネズミ捕り",
  "サメの襲撃",
  "蜘蛛の巣",
  "アリの巣",
  "蜂の巣",
  "カニ歩き",
  "イルカのジャンプ",
  "ゾウの鼻",
  "キリンの首",
  "カバのあくび",
  "コアラのハグ",
  "ラマの唾",
  "ミーアキャットの見張り",
  "イッカクの角",
  "フクロウの鳴き声",
  "オウムのおしゃべり",
  "ウズラの卵",
  "アライグマの仮面",
  "アシカの拍手",
  "カメの甲羅",
  "ハゲタカの旋回",
  "セイウチの牙",
  "ヤクのバター",
  "ジップライン",
  "バナナスプリット",
  "コーンドッグ",
  "ドーナツの穴",
  "春巻き",
  "フィッシュタコス",
  "ブドウの蔓",
  "ハンバーガー",
  "アイスキャンディー",
  "ジャムの瓶",
  "キウイフルーツ",
  "ライムグリーン",
  "マンゴーサルサ",
  "くるみ割り人形",
  "オリーブの枝",
  "ピーチコブラー",
  "おにぎり",
  "巻き寿司",
  "タコスの屋台",
  "ベジバーガー",
  "ワッフルコーン",
  "りんご飴",
  "グミベア",
  "ジェリービーンズ",
  "ペロペロキャンディー",
  "マシュマロ",
  "ポップコーンの袋",
  "プレッツェル",
  "チーズの丸",
  "パンのかご",
  "バターカップ",
  "カップケーキ",
  "パンケーキの山",
  "フレンチトースト",
  "目玉焼き",
  "ベーコン",
  "コーヒーカップ",
  "急須",
  "ミルクセーキ",
  "スムージーボウル",
  "フルーツパンチ",
  "レモネード",
  "炭酸ジュース",
  "ルートビア",
  "ジンジャースナップ",
  "シナモンロール",
  "パンプキンパイ",
  "キャロットケーキ",
  "レッドベルベット",
  "エンジェルケーキ",
  "悪魔の角",
  "魔女の帽子",
  "魔法使いの杖",
  "竜の卵",
  "不死鳥の翼",
  "グリフォンの爪",
  "人魚のしっぽ",
  "ケンタウロスの疾走",
  "妖精の粉",
  "ピクシーの羽",
  "エルフの耳",
  "ドワーフの斧",
  "ゴブリンの金",
  "トロルの橋",
  "巨人の一歩",
  "騎士の鎧",
  "城の塔",
  "お堀の水",
  "跳ね橋",
  "玉座の間",
  "王室の宴",
  "魔法の鏡",
  "毒リンゴ",
  "ガラスの靴",
  "カボチャの馬車",
  "紡ぎ車",
  "魔法の森",
  "呪いの指輪",
  "隠れた洞窟",
  "秘密の通路",
  "宝箱",
  "金貨",
  "銀の鍵",
  "青銅の盾",
  "鉄の剣",
  "ダイヤの指輪",
  "ルビーの靴",
  "エメラルドの都",
  "サファイアの空",
  "真珠のネックレス",
  "サンゴ礁",
  "溶岩の流れ",
  "水晶の洞窟",
  "琥珀の石",
  "翡翠の庭",
  "トパーズの太陽",
  "オパールの月",
  "雲の城",
  "空の橋",
  "星の門",
  "日時計",
  "月の光",
  "彗星のしっぽ",
  "流星群",
  "銀河の渦",
  "星雲の雲",
  "ブラックホール",
  "タイムマシン",
  "ロボット軍団",
  "レーザービーム",
  "バリアフィールド",
  "ジェットパック",
  "ホバーボード",
  "ワープ速度",
  "宇宙人の船",
  "宇宙遊泳",
  "月面基地",
  "火星探査車",
  "土星の輪",
  "星のかけら",
  "宇宙線",
  "太陽フレア",
  "オーロラ",
  "南十字星",
  "貿易風",
  "津波",
  "地震",
  "砂嵐",
  "熱波",
  "寒波",
  "雨雲",
  "雪の結晶",
  "あられ",
  "稲妻",
  "雷鳴",
  "竜巻の回転",
  "水門",
  "地滑り",
  "落石",
  "雪崩",
  "間欠泉の噴出",
  "温泉",
  "滝の落下",
  "川の曲がり",
  "湖の岸",
  "池の蓮",
  "小川の底",
  "湿地帯",
  "沼の怪物",
  "ジャングルの蔓",
  "熱帯雨林",
  "竹林",
  "柳の木",
  "樫の木",
  "松ぼっくり",
  "紅葉の葉",
  "どんぐりの帽子",
  "苔むした岩",
  "シダの葉",
  "サボテンの花",
  "ひまわり",
  "チューリップ畑",
  "バラの庭",
  "デイジーの花輪",
  "すみれの花",
  "蘭の茎",
  "蓮の葉",
  "蓮の池",
  "クローバーの丘",
  "キノコの傘",
  "ベリーの茂み",
  "リンゴの木",
  "レモンの木",
  "桃の木",
  "梅の花",
  "いちじくの葉",
  "ココナッツヤシ",
  "バナナの皮",
  "パイナップルの頭",
  "いちご畑",
  "ブルーベリーの丘",
  "ラズベリージャム",
  "スイカの一切れ",
  "メロンボール",
  "洋梨のしずく",
  "さくらんぼ爆弾",
  "オリーブオイル",
  "とうもろこし畑",
  "小麦の穂",
  "田んぼ",
  "ジャガイモの袋",
  "トマトソース",
  "コショウ挽き",
  "オニオンリング",
  "ガーリックトースト",
  "ハーブガーデン",
  "スパイスラック",
  "塩の湖",
  "サトウキビ",
  "蜂蜜の壺",
  "メープルシロップ",
  "バニラビーンズ",
  "カカオ豆",
  "コーヒー豆",
  "茶葉",
  "ミントの葉",
  "バジルの鉢",
  "絵筆",
  "色相環",
  "スケッチブック",
  "陶器の壺",
  "木彫り",
  "折り鶴",
  "墨のしみ",
  "黒板",
  "クレヨンの箱",
  "筆箱",
  "本の虫",
  "ページめくり",
  "絵本",
  "漫画",
  "オルゴール",
  "ドラムロール",
  "ピアノの鍵盤",
  "バイオリンの弓",
  "トランペットの音",
  "フルートの歌",
  "ハープの弦",
  "鐘楼",
  "風鈴",
  "玄関のベル",
  "目覚まし時計",
  "砂時計",
  "懐中時計",
  "サングラス",
  "シルクハット",
  "蝶ネクタイ",
  "レッドカーペット",
  "スポットライト",
  "舞台恐怖",
  "カーテンコール",
  "スタンディングオベーション",
  "アンコール公演",
  "グランドフィナーレ",
  "花火",
  "紙吹雪の雨",
  "風船の旅",
  "凧揚げ",
  "紙飛行機",
  "おもちゃの列車",
  "ドールハウス",
  "テディベアのピクニック",
  "パズルのピース",
  "ボードゲーム",
  "カードマジック",
  "サイコロの目",
  "チェスのナイト",
  "王冠の宝石",
  "幸運のお守り",
  "願い骨",
  "ドリームキャッチャー",
  "風車",
  "灯台",
  "見張りの塔",
  "時計台",
  "給水塔",
  "電波塔",
  "観覧車",
  "メリーゴーラウンド",
  "バンパーカー",
  "お化け屋敷",
  "わたあめ機",
  "景品コーナー",
  "輪投げ",
  "アヒルの池",
  "ふれあい動物園",
  "干し草の馬車",
  "トウモロコシ迷路",
  "カボチャ畑",
  "リンゴ園",
  "ベリー狩り",
  "花の冠",
  "落ち葉の山",
  "雪の天使",
  "砂の城",
  "泥だんご",
  "石の塔",
  "貝殻集め",
  "流木",
  "シーグラス",
  "潮だまり",
  "ヤドカリ",
  "ヒトデ",
  "タツノオトシゴ",
  "フグ",
  "メカジキ",
  "クマノミ",
  "エンゼルフィッシュ",
  "シュモクザメ",
  "アカエイ",
  "デンキウナギ",
  "イカスミ",
  "クジラの尻尾",
  "アザラシの子",
  "カワウソの滑り台",
  "ペンギンの行進",
  "ペリカンの急降下",
  "カモメの鳴き声",
  "アホウドリの滑空",
  "孔雀の歩き",
  "フラミンゴ立ち",
  "サギの魚獲り",
  "コマドリの歌",
  "スズメの跳び",
  "赤い鶴",
  "カケスの青",
  "ハチドリ",
  "キツツキ",
  "ハクトウワシ",
  "鷹の眼",
  "ハヤブサの急降下",
  "平和のハト",
  "焚き火の歌",
  "お菓子屋さん",
  "三日月",
  "踊る炎",
  "落ちる葉",
  "庭の小人",
  "光るランタン",
  "蹄鉄の幸運",
  "笑うハイエナ",
  "魔法のじゅうたん",
  "朝の露",
  "麺のスープ",
  "眠いナマケモノ",
  "ヒトデの浜辺",
  "夕焼けの輝き",
  "南国の鳥",
  "暖かい毛布",
];
