const en = {
  gameName: "Word Rush",
  shortName: "Word Rush",
  tagline: "Guess the word from 3 emoji. Learn it. Say it!",
  dirJa: "日本語の人 → English",
  dirEn: "English speakers → 日本語",
  pack: "Word pack",
  packs: {
    mix: "Mix",
    foodie: "Foodie",
    travel: "Travel",
    slang: "Slang",
    anime: "Anime",
    feelings: "Feelings",
    chat: "From this chat",
  } as Record<string, string>,
  sayIt: "Say it!",
  sayItDesc: "Every 2nd word, someone takes the mic",
  on: "ON",
  off: "OFF",
  dealing: "Dealing fresh cards…",
  dealt: "Fresh cards ready!",
  players: (n: number) => `${n} player${n === 1 ? "" : "s"}`,
  learning: "learning",
  host: "host",
  you: "you",
  join: "JOIN!",
  notNow: "Not now",
  start: "START WORD RUSH!",
  cancel: "Cancel",
  leave: "Leave",
  waitingHost: "Waiting for the host to start…",
  needTwo: "Say it! needs 2+ players",
  pillLobby: "Word Rush lobby",
  pillCard: (i: number, n: number) => `Word Rush · card ${i}/${n}`,
  pillResults: "Word Rush · results",
  joinShort: "JOIN",
  minimize: "Minimize",
  menuSkip: "Skip ahead",
  menuEnd: "End game",
  confirmEnd: "End Word Rush for everyone?",
  fasterMore: "faster = more points",
  askEn: "What's this in English?",
  askJa: "What's this in Japanese?",
  hint: "Hint",
  hintLocked: "Hint",
  streak: (n: number) => `${n} in a row`,
  score: "score",
  lockedIn: "LOCKED IN!",
  inCount: (a: number, b: number) => `${a}/${b} in`,
  mascotEarly: "One more emoji might give it away…!",
  mascotAll: "All 3 are out — go go go!",
  mascotLocked: "Locked in! Waiting for the others…",
  mascotSpectate: "You're watching this round",
  spectating: "Spectating",
  gotIt: "GOT\nIT!",
  miss: "miss",
  missed: "MISS…",
  tooSlow: "TIME!",
  speak: "Hear it",
  sayItNext: "SAY IT! IS NEXT",
  nextIn: (s: number) => `Next word in ${s}s`,
  nextWord: "NEXT WORD ➜",
  yourTurn: "YOUR TURN ON THE MIC!",
  onTheMic: "ON THE MIC!",
  sayItTitle: "Say it!",
  holdOrTap: "Hold to record · or tap to start/stop (4s max)",
  recording: (s: string) => `● REC ${s} · release to stop`,
  recordingTap: (s: string) => `● REC ${s} · tap to stop`,
  preview: "Your take",
  retake: "Retake",
  tryAgain: "Try again",
  send: "SEND!",
  sending: "Sending…",
  skip: "Skip",
  micDenied: "Mic access is blocked. Allow the microphone in your browser settings, or skip this one.",
  micUnsupported: "This browser can't record audio. Skip this one!",
  micFailed: "Couldn't start the mic. Try again or skip.",
  judgesLabel: "Judges",
  judgesNote: (lang: string) => `${lang === "en" ? "English" : "Japanese"} natives' votes count ×2`,
  nativeX2: "NATIVE ×2",
  isOnMic: (n: string) => `${n}'s on the mic!`,
  getReady: "Get your judging thumbs ready…",
  listenIn: "Listen in — the players will judge",
  saidIt: (n: string) => `${n} said it!`,
  howDid: (n: string) => `How did ${n} do?`,
  huh: "Huh?",
  huhSub: "try again!",
  close: "Close!",
  closeSub: "almost there",
  native: "Native!",
  nativeSub: "nailed it",
  countsDouble: "your vote counts double",
  teach: (n: string) => `Teach ${n}`,
  teachSub: "record how you say it",
  teachSending: "Sending…",
  teachSent: "Sent! They'll hear your version",
  teachTaken: (n: string) => `${n} already taught this one`,
  tapToPlay: "Tap to play",
  roomJudging: "The room is judging…",
  votedCount: (a: number, b: number) => `${a}/${b} voted`,
  noClip: "No clip came through",
  verdictNative: "NATIVE!",
  verdictClose: "CLOSE!",
  verdictHuh: "HUH?",
  bonus: (n: number) => `+${n} BONUS`,
  noVotes: "Nobody voted this time",
  hearVersion: (n: string) => `${n}'s version`,
  resultsTitle: "BRAIN JUICE!!",
  wordsThisGame: "Words this game",
  tapToHear: "tap to hear",
  bestStreak: "streak",
  correct: "correct",
  sayItBonus: "say it",
  backToChat: "BACK TO CHAT",
  again: "AGAIN!",
  pts: "pts",
  error: "Something went wrong",
};

type Dict = typeof en;

const ja: Dict = {
  gameName: "ワードラッシュ",
  shortName: "ワードラッシュ",
  tagline: "3つの絵文字から単語を当てて、覚えて、言ってみよう！",
  dirJa: "日本語の人 → English",
  dirEn: "English speakers → 日本語",
  pack: "単語パック",
  packs: {
    mix: "ミックス",
    foodie: "グルメ",
    travel: "旅行",
    slang: "スラング",
    anime: "アニメ",
    feelings: "気持ち",
    chat: "このチャットから",
  },
  sayIt: "言ってみよう！",
  sayItDesc: "2問ごとに誰かがマイクで発音チャレンジ",
  on: "ON",
  off: "OFF",
  dealing: "新しいカードを配っています…",
  dealt: "新しいカードの準備OK！",
  players: (n: number) => `${n}人`,
  learning: "学習中",
  host: "ホスト",
  you: "あなた",
  join: "参加する！",
  notNow: "あとで",
  start: "ワードラッシュ開始！",
  cancel: "キャンセル",
  leave: "抜ける",
  waitingHost: "ホストの開始を待っています…",
  needTwo: "言ってみよう！は2人以上で",
  pillLobby: "ワードラッシュ ロビー",
  pillCard: (i: number, n: number) => `ワードラッシュ · ${i}/${n}問`,
  pillResults: "ワードラッシュ · 結果",
  joinShort: "参加",
  minimize: "最小化",
  menuSkip: "次へスキップ",
  menuEnd: "ゲーム終了",
  confirmEnd: "全員のワードラッシュを終了しますか？",
  fasterMore: "早いほど高得点",
  askEn: "この絵文字、なんて英語？",
  askJa: "この絵文字、日本語で何？",
  hint: "ヒント",
  hintLocked: "ヒント",
  streak: (n: number) => `${n}連続`,
  score: "スコア",
  lockedIn: "決定！",
  inCount: (a: number, b: number) => `${a}/${b}人 回答`,
  mascotEarly: "あと1つで答えが見えるかも…！",
  mascotAll: "3つ揃った！いそげ〜！",
  mascotLocked: "決定！みんなを待ってるよ…",
  mascotSpectate: "観戦中だよ",
  spectating: "観戦中",
  gotIt: "正解\n！",
  miss: "ミス",
  missed: "ざんねん…",
  tooSlow: "時間切れ！",
  speak: "聞く",
  sayItNext: "次は「言ってみよう！」",
  nextIn: (s: number) => `あと${s}秒で次の単語`,
  nextWord: "次の単語 ➜",
  yourTurn: "あなたがマイクの番！",
  onTheMic: "マイクオン！",
  sayItTitle: "言ってみよう！",
  holdOrTap: "長押しで録音・タップで開始/停止（最大4秒）",
  recording: (s: string) => `● REC ${s} · 離すと停止`,
  recordingTap: (s: string) => `● REC ${s} · タップで停止`,
  preview: "あなたの録音",
  retake: "録り直す",
  tryAgain: "もう一度",
  send: "送信！",
  sending: "送信中…",
  skip: "スキップ",
  micDenied: "マイクがブロックされています。ブラウザ設定でマイクを許可するか、今回はスキップしてね。",
  micUnsupported: "このブラウザでは録音できません。今回はスキップしてね！",
  micFailed: "マイクを開始できませんでした。もう一度試すかスキップしてね。",
  judgesLabel: "審査員",
  judgesNote: (lang: string) => `${lang === "en" ? "英語" : "日本語"}ネイティブの票は2倍`,
  nativeX2: "NATIVE ×2",
  isOnMic: (n: string) => `${n}さんがマイクの番！`,
  getReady: "審査の準備をしてね…",
  listenIn: "聞いててね — 審査はプレイヤーが担当",
  saidIt: (n: string) => `${n}さんが言った！`,
  howDid: (n: string) => `${n}さんの発音はどうだった？`,
  huh: "え？",
  huhSub: "もう一回！",
  close: "おしい！",
  closeSub: "あと少し",
  native: "ネイティブ！",
  nativeSub: "完璧！",
  countsDouble: "あなたの票は2倍",
  teach: (n: string) => `${n}さんにお手本`,
  teachSub: "あなたの発音を録音",
  teachSending: "送信中…",
  teachSent: "送信しました！お手本が届きます",
  teachTaken: (n: string) => `${n}さんがもうお手本を送りました`,
  tapToPlay: "タップで再生",
  roomJudging: "みんなが審査中…",
  votedCount: (a: number, b: number) => `${a}/${b}人 投票`,
  noClip: "録音が届きませんでした",
  verdictNative: "ネイティブ級！",
  verdictClose: "おしい！",
  verdictHuh: "え？？",
  bonus: (n: number) => `+${n} ボーナス`,
  noVotes: "今回は投票なし",
  hearVersion: (n: string) => `${n}さんのお手本`,
  resultsTitle: "脳汁ドバドバ!!",
  wordsThisGame: "今回の単語",
  tapToHear: "タップで再生",
  bestStreak: "連続",
  correct: "正解",
  sayItBonus: "発音",
  backToChat: "チャットに戻る",
  again: "もう一回！",
  pts: "点",
  error: "エラーが発生しました",
};

export type WordRushStrings = Dict;

export function stringsFor(lang: string): WordRushStrings {
  return lang === "ja" ? ja : en;
}
