import { JaWord } from "./wordRushShared";

export interface RawCard {
  en: string;
  ja: JaWord;
  ipa: string;
  posEn: string;
  posJa: string;
  emoji: string[];
  hookEn: string;
  hookJa: string;
  exampleEn: string;
  exampleJa: string;
  scene: string;
  wrongEn: string[];
  wrongJa: JaWord[];
}

const j = (ja: string, kana: string, romaji: string): JaWord => ({ ja, kana, romaji });

// Offline deck used when the Anthropic call fails or no key is configured.
export const FALLBACK_DECK: Array<RawCard & { packs: string[] }> = [
  {
    packs: ["travel", "feelings"],
    en: "cherry blossom",
    ja: j("桜", "さくら", "sakura"),
    ipa: "/ˈtʃɛri ˈblɒsəm/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🌸", "🌳", "🌤️"],
    hookEn: "SAKURA → 'sock-oo-ra': petals stuck in your sock every spring.",
    hookJa: "チェリー（さくらんぼ）の木のブロッサム（花）＝桜！",
    exampleEn: "The cherry blossoms are falling like snow.",
    exampleJa: "桜が雪みたいに散っている。",
    scene: "petals",
    wrongEn: ["sunflower", "maple leaf", "tulip"],
    wrongJa: [j("向日葵", "ひまわり", "himawari"), j("紅葉", "もみじ", "momiji"), j("梅", "うめ", "ume")],
  },
  {
    packs: ["slang", "foodie"],
    en: "hangry",
    ja: j("腹ペコでイライラ", "はらぺこでいらいら", "harapeko de iraira"),
    ipa: "/ˈhæŋɡri/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["😤", "🍔", "💢"],
    hookEn: "HARAPEKO = empty belly, IRAIRA = grr. Together: hangry.",
    hookJa: "hungry（空腹）＋ angry（怒り）＝ hangry！",
    exampleEn: "Feed me before I get hangry!",
    exampleJa: "腹ペコでイライラする前に何か食べさせて！",
    scene: "confetti",
    wrongEn: ["sleepy", "bored", "stuffed"],
    wrongJa: [j("眠い", "ねむい", "nemui"), j("退屈", "たいくつ", "taikutsu"), j("満腹", "まんぷく", "manpuku")],
  },
  {
    packs: ["travel"],
    en: "umbrella",
    ja: j("傘", "かさ", "kasa"),
    ipa: "/ʌmˈbrɛlə/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["☔", "🌧️", "🚶"],
    hookEn: "KASA sounds like 'casa' — a little house for your head.",
    hookJa: "アンブレラ…雨（あめ）をブロックする傘！",
    exampleEn: "Don't forget your umbrella, it's raining.",
    exampleJa: "雨だから傘を忘れないでね。",
    scene: "bubbles",
    wrongEn: ["raincoat", "cloud", "puddle"],
    wrongJa: [j("雲", "くも", "kumo"), j("水たまり", "みずたまり", "mizutamari"), j("長靴", "ながぐつ", "nagagutsu")],
  },
  {
    packs: ["foodie"],
    en: "delicious",
    ja: j("美味しい", "おいしい", "oishii"),
    ipa: "/dɪˈlɪʃəs/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["😋", "🍜", "✨"],
    hookEn: "OISHII — say 'oh, she-ee!' when the food is that good.",
    hookJa: "デリ（惣菜屋）に並ぶのは美味しいもの＝delicious",
    exampleEn: "This ramen is so delicious!",
    exampleJa: "このラーメン、すごく美味しい！",
    scene: "sparkles",
    wrongEn: ["spicy", "gross", "hungry"],
    wrongJa: [j("辛い", "からい", "karai"), j("まずい", "まずい", "mazui"), j("熱い", "あつい", "atsui")],
  },
  {
    packs: ["travel"],
    en: "train station",
    ja: j("駅", "えき", "eki"),
    ipa: "/treɪn ˈsteɪʃən/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🚉", "🚃", "🎫"],
    hookEn: "EKI — 'eh, key?': the station is the key to the whole city.",
    hookJa: "ステーション＝電車がステイ（止まる）場所＝駅",
    exampleEn: "Meet me at the train station at noon.",
    exampleJa: "お昼に駅で会おう。",
    scene: "stars",
    wrongEn: ["airport", "ticket", "bus stop"],
    wrongJa: [j("空港", "くうこう", "kūkō"), j("切符", "きっぷ", "kippu"), j("線路", "せんろ", "senro")],
  },
  {
    packs: ["feelings"],
    en: "sleepy",
    ja: j("眠い", "ねむい", "nemui"),
    ipa: "/ˈsliːpi/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["😪", "🌙", "🛏️"],
    hookEn: "NEMUI — like Nemo slowly drifting off to sleep.",
    hookJa: "スリープ（眠る）＋ y ＝ スリーピー＝眠い",
    exampleEn: "I'm so sleepy after lunch.",
    exampleJa: "お昼ご飯のあと、すごく眠い。",
    scene: "stars",
    wrongEn: ["hungry", "lonely", "dizzy"],
    wrongJa: [j("寂しい", "さびしい", "sabishii"), j("暇", "ひま", "hima"), j("寒い", "さむい", "samui")],
  },
  {
    packs: ["feelings"],
    en: "friend",
    ja: j("友達", "ともだち", "tomodachi"),
    ipa: "/frɛnd/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🤝", "😊", "👫"],
    hookEn: "TOMODACHI — 'tomorrow, dutch?' is what friends ask each other.",
    hookJa: "fri-END ＝ 最後（END）まで一緒にいる友達",
    exampleEn: "She's my best friend.",
    exampleJa: "彼女は私の一番の友達です。",
    scene: "hearts",
    wrongEn: ["neighbor", "teacher", "stranger"],
    wrongJa: [j("先生", "せんせい", "sensei"), j("家族", "かぞく", "kazoku"), j("隣人", "りんじん", "rinjin")],
  },
  {
    packs: ["travel"],
    en: "fireworks",
    ja: j("花火", "はなび", "hanabi"),
    ipa: "/ˈfaɪərwɜːrks/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🎆", "🌃", "🎇"],
    hookEn: "HANA (flower) + BI (fire) = fire flowers!",
    hookJa: "fire（火）＋ works（作品）＝ 空に咲く火の作品＝花火",
    exampleEn: "Let's watch the fireworks tonight.",
    exampleJa: "今夜、花火を見に行こう。",
    scene: "confetti",
    wrongEn: ["lanterns", "lightning", "campfire"],
    wrongJa: [j("提灯", "ちょうちん", "chōchin"), j("雷", "かみなり", "kaminari"), j("星空", "ほしぞら", "hoshizora")],
  },
  {
    packs: ["feelings"],
    en: "embarrassed",
    ja: j("恥ずかしい", "はずかしい", "hazukashii"),
    ipa: "/ɪmˈbærəst/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["😳", "🙈", "💦"],
    hookEn: "HAZUKASHII — 'has a car, she?' Nope. So embarrassing.",
    hookJa: "em-BARRA-ssed ＝ 顔がバラ色に赤くなる！",
    exampleEn: "I was so embarrassed I turned red.",
    exampleJa: "恥ずかしくて顔が赤くなった。",
    scene: "hearts",
    wrongEn: ["proud", "angry", "sneaky"],
    wrongJa: [j("嬉しい", "うれしい", "ureshii"), j("怖い", "こわい", "kowai"), j("悔しい", "くやしい", "kuyashii")],
  },
  {
    packs: ["foodie"],
    en: "breakfast",
    ja: j("朝ごはん", "あさごはん", "asagohan"),
    ipa: "/ˈbrɛkfəst/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🌅", "🍳", "🍞"],
    hookEn: "ASA (morning) + GOHAN (rice / meal) = morning meal.",
    hookJa: "break（破る）＋ fast（断食）＝ 夜の断食を破る朝ごはん",
    exampleEn: "What did you eat for breakfast?",
    exampleJa: "朝ごはんに何を食べた？",
    scene: "sparkles",
    wrongEn: ["dinner", "snack", "lunch box"],
    wrongJa: [j("晩ごはん", "ばんごはん", "bangohan"), j("お弁当", "おべんとう", "obentō"), j("おやつ", "おやつ", "oyatsu")],
  },
  {
    packs: ["foodie"],
    en: "strawberry",
    ja: j("いちご", "いちご", "ichigo"),
    ipa: "/ˈstrɔːbəri/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🍓", "🍰", "❤️"],
    hookEn: "ICHIGO — 'itchy go': those little seeds tickle your tongue.",
    hookJa: "ストロー（わら）を敷いて育てるベリー＝いちご",
    exampleEn: "This strawberry cake is amazing.",
    exampleJa: "このいちごケーキ最高！",
    scene: "hearts",
    wrongEn: ["cherry", "tomato", "raspberry"],
    wrongJa: [j("さくらんぼ", "さくらんぼ", "sakuranbo"), j("りんご", "りんご", "ringo"), j("桃", "もも", "momo")],
  },
  {
    packs: ["travel", "mix"],
    en: "snowman",
    ja: j("雪だるま", "ゆきだるま", "yukidaruma"),
    ipa: "/ˈsnoʊmæn/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["⛄", "❄️", "🧣"],
    hookEn: "YUKI (snow) + DARUMA (round lucky doll) = snow daruma.",
    hookJa: "snow（雪）＋ man（人）＝ 雪の人＝雪だるま",
    exampleEn: "The kids built a huge snowman.",
    exampleJa: "子どもたちが大きな雪だるまを作った。",
    scene: "snow",
    wrongEn: ["igloo", "snowball", "scarf"],
    wrongJa: [j("雪合戦", "ゆきがっせん", "yukigassen"), j("つらら", "つらら", "tsurara"), j("かまくら", "かまくら", "kamakura")],
  },
  {
    packs: ["travel"],
    en: "hot spring",
    ja: j("温泉", "おんせん", "onsen"),
    ipa: "/hɒt sprɪŋ/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["♨️", "🛁", "🏔️"],
    hookEn: "ON (warm) + SEN (spring): turn the heat ON.",
    hookJa: "hot（熱い）＋ spring（湧き出る泉）＝ 温泉",
    exampleEn: "Let's relax in a hot spring.",
    exampleJa: "温泉でゆっくりしよう。",
    scene: "bubbles",
    wrongEn: ["swimming pool", "waterfall", "sauna"],
    wrongJa: [j("滝", "たき", "taki"), j("銭湯", "せんとう", "sentō"), j("海", "うみ", "umi")],
  },
  {
    packs: ["slang"],
    en: "awesome",
    ja: j("すごい", "すごい", "sugoi"),
    ipa: "/ˈɔːsəm/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["🤩", "🔥", "👏"],
    hookEn: "SUGOI — 'sue, go-y!': what you yell when it's awesome.",
    hookJa: "awe（畏敬）＋ some ＝ 思わず「おぉ」となる＝すごい",
    exampleEn: "Your drawing is awesome!",
    exampleJa: "君の絵、すごいね！",
    scene: "sparkles",
    wrongEn: ["awkward", "boring", "scary"],
    wrongJa: [j("ひどい", "ひどい", "hidoi"), j("危ない", "あぶない", "abunai"), j("怪しい", "あやしい", "ayashii")],
  },
  {
    packs: ["feelings"],
    en: "tired",
    ja: j("疲れた", "つかれた", "tsukareta"),
    ipa: "/ˈtaɪərd/",
    posEn: "adjective",
    posJa: "形容詞",
    emoji: ["😩", "💼", "🛋️"],
    hookEn: "TSUKARETA — 'ski-car-ate-a': skied all day, now totally tired.",
    hookJa: "tire（タイヤ）がすり減るくらい疲れた",
    exampleEn: "I'm tired, let's go home.",
    exampleJa: "疲れた、帰ろう。",
    scene: "stars",
    wrongEn: ["excited", "busy", "nervous"],
    wrongJa: [j("忙しい", "いそがしい", "isogashii"), j("楽しい", "たのしい", "tanoshii"), j("緊張", "きんちょう", "kinchō")],
  },
  {
    packs: ["anime"],
    en: "transform",
    ja: j("変身", "へんしん", "henshin"),
    ipa: "/trænsˈfɔːrm/",
    posEn: "verb",
    posJa: "動詞",
    emoji: ["✨", "🦸", "💫"],
    hookEn: "HENSHIN — a hen kicks its shin and becomes a hero.",
    hookJa: "trans（越えて）＋ form（形）＝ 形を越える＝変身",
    exampleEn: "The hero transforms in a flash of light.",
    exampleJa: "ヒーローが光とともに変身する。",
    scene: "sparkles",
    wrongEn: ["explode", "teleport", "disappear"],
    wrongJa: [j("消える", "きえる", "kieru"), j("爆発", "ばくはつ", "bakuhatsu"), j("瞬間移動", "しゅんかんいどう", "shunkan idō")],
  },
  {
    packs: ["anime"],
    en: "sword",
    ja: j("刀", "かたな", "katana"),
    ipa: "/sɔːrd/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["⚔️", "🥷", "✨"],
    hookEn: "KATANA — you know this one from every samurai movie.",
    hookJa: "sword の w は読まない！「ソード」＝刀",
    exampleEn: "The samurai drew his sword.",
    exampleJa: "侍が刀を抜いた。",
    scene: "stars",
    wrongEn: ["shield", "arrow", "spear"],
    wrongJa: [j("盾", "たて", "tate"), j("弓", "ゆみ", "yumi"), j("槍", "やり", "yari")],
  },
  {
    packs: ["anime", "feelings"],
    en: "wish",
    ja: j("願い", "ねがい", "negai"),
    ipa: "/wɪʃ/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🌠", "🙏", "✨"],
    hookEn: "NEGAI — 'nay, guy!': say it out loud and it won't come true.",
    hookJa: "ウィッシュ＝流れ星にシュッとお願い＝願い",
    exampleEn: "Make a wish on a shooting star.",
    exampleJa: "流れ星に願いごとをしよう。",
    scene: "stars",
    wrongEn: ["dream", "promise", "secret"],
    wrongJa: [j("夢", "ゆめ", "yume"), j("約束", "やくそく", "yakusoku"), j("秘密", "ひみつ", "himitsu")],
  },
  {
    packs: ["slang", "anime"],
    en: "no way!",
    ja: j("まさか", "まさか", "masaka"),
    ipa: "/noʊ weɪ/",
    posEn: "expression",
    posJa: "表現",
    emoji: ["😱", "❗", "🤯"],
    hookEn: "MASAKA — 'mama saw ka-boom?!' No way!",
    hookJa: "no way ＝ 道（way）が無い＝ありえない＝まさか！",
    exampleEn: "No way! You met her?",
    exampleJa: "まさか！彼女に会ったの？",
    scene: "confetti",
    wrongEn: ["of course!", "be careful!", "good luck!"],
    wrongJa: [j("もちろん", "もちろん", "mochiron"), j("気をつけて", "きをつけて", "ki o tsukete"), j("がんばって", "がんばって", "ganbatte")],
  },
  {
    packs: ["mix"],
    en: "music",
    ja: j("音楽", "おんがく", "ongaku"),
    ipa: "/ˈmjuːzɪk/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🎵", "🎧", "🎶"],
    hookEn: "ON (sound) + GAKU (enjoyment) = sound you enjoy.",
    hookJa: "ミュージック＝ミューズ（芸術の女神）の技＝音楽",
    exampleEn: "I listen to music on the train.",
    exampleJa: "電車で音楽を聴く。",
    scene: "notes",
    wrongEn: ["noise", "dance", "poem"],
    wrongJa: [j("踊り", "おどり", "odori"), j("歌詞", "かし", "kashi"), j("騒音", "そうおん", "sōon")],
  },
  {
    packs: ["foodie"],
    en: "rice ball",
    ja: j("おにぎり", "おにぎり", "onigiri"),
    ipa: "/raɪs bɔːl/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🍙", "🧺", "😋"],
    hookEn: "ONIGIRI comes from NIGIRU, 'to squeeze': squeezed rice.",
    hookJa: "rice（ご飯）＋ ball（ボール）＝ ご飯のボール＝おにぎり",
    exampleEn: "I packed rice balls for the picnic.",
    exampleJa: "ピクニックにおにぎりを持ってきた。",
    scene: "sparkles",
    wrongEn: ["sushi roll", "dumpling", "rice cake"],
    wrongJa: [j("餃子", "ぎょうざ", "gyōza"), j("巻き寿司", "まきずし", "makizushi"), j("お餅", "おもち", "omochi")],
  },
  {
    packs: ["travel", "mix"],
    en: "summer festival",
    ja: j("夏祭り", "なつまつり", "natsumatsuri"),
    ipa: "/ˈsʌmər ˈfɛstɪvəl/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["🏮", "👘", "🍧"],
    hookEn: "NATSU (summer) + MATSURI (festival). Lanterns and shaved ice!",
    hookJa: "summer（夏）＋ festival（祭り）＝ そのまま夏祭り！",
    exampleEn: "We wore yukata to the summer festival.",
    exampleJa: "夏祭りに浴衣を着て行った。",
    scene: "confetti",
    wrongEn: ["fireworks", "beach trip", "new year"],
    wrongJa: [j("花見", "はなみ", "hanami"), j("お正月", "おしょうがつ", "oshōgatsu"), j("海水浴", "かいすいよく", "kaisuiyoku")],
  },
  {
    packs: ["feelings", "slang"],
    en: "crush",
    ja: j("片思い", "かたおもい", "kataomoi"),
    ipa: "/krʌʃ/",
    posEn: "noun",
    posJa: "名詞",
    emoji: ["💘", "🙈", "💭"],
    hookEn: "KATA (one side) + OMOI (feelings) = one-sided love.",
    hookJa: "crush ＝ 心がクシャッと潰れるほど好き＝片思い",
    exampleEn: "I have a crush on someone in my class.",
    exampleJa: "クラスの人に片思いしている。",
    scene: "hearts",
    wrongEn: ["breakup", "best friend", "first date"],
    wrongJa: [j("失恋", "しつれん", "shitsuren"), j("初デート", "はつでーと", "hatsu dēto"), j("親友", "しんゆう", "shin'yū")],
  },
  {
    packs: ["slang", "mix"],
    en: "chill",
    ja: j("まったり", "まったり", "mattari"),
    ipa: "/tʃɪl/",
    posEn: "verb",
    posJa: "動詞",
    emoji: ["😌", "🛋️", "🍵"],
    hookEn: "MATTARI — 'mat tarry': tarry on the mat, nice and chill.",
    hookJa: "chill ＝ ひんやり→熱くならない＝まったり",
    exampleEn: "Let's just chill at home today.",
    exampleJa: "今日は家でまったりしよう。",
    scene: "bubbles",
    wrongEn: ["rush", "party", "panic"],
    wrongJa: [j("バタバタ", "ばたばた", "batabata"), j("わくわく", "わくわく", "wakuwaku"), j("ドキドキ", "どきどき", "dokidoki")],
  },
];
