import Foundation

/// Minimal i18n — keyed by English string, with Japanese translations.
enum L {
    private static let translations: [String: [String: String]] = [
        // Start room
        "Enchatto": ["ja": "Enchatto"],
        "Create a conversation room": ["ja": "会話ルームを作成"],
        "CHAT ACROSS LANGUAGES": ["ja": "ことばの壁をこえよう"],
        "Your nickname": ["ja": "ニックネーム"],
        "Enter your name": ["ja": "名前を入力"],
        "Choose your avatar": ["ja": "アバターを選ぶ"],
        "Your language": ["ja": "あなたの言語"],
        "English": ["ja": "英語"],
        "Japanese": ["ja": "日本語"],
        "Create Room": ["ja": "ルームを作成"],

        // Conversation
        "Loading...": ["ja": "読み込み中…"],
        "Processing...": ["ja": "処理中…"],
        "No messages yet": ["ja": "まだメッセージがありません"],
        "Waiting for participants to start chatting": ["ja": "参加者がチャットを始めるのを待っています"],
        "Type a message...": ["ja": "メッセージを入力…"],
        "Camera": ["ja": "カメラ"],
        "Draw": ["ja": "描く"],
        "Voice": ["ja": "音声"],

        // Reply
        "Replying to": ["ja": "返信先:"],
        "Unknown": ["ja": "不明"],

        // Close room
        "Close this room?": ["ja": "このルームを閉じますか？"],
        "Close Room": ["ja": "ルームを閉じる"],
        "All participants will be disconnected. This cannot be undone.": [
            "ja": "すべての参加者が切断されます。この操作は元に戻せません。"
        ],

        // Closed banner
        "This room has been closed": ["ja": "このルームは閉鎖されました"],
        "Back to Home": ["ja": "ホームに戻る"],

        // Participants
        "Participants": ["ja": "参加者"],
        "Settings": ["ja": "設定"],
        "Done": ["ja": "完了"],
        "host": ["ja": "ホスト"],
        "Online": ["ja": "オンライン"],
        "Offline": ["ja": "オフライン"],
        "Away": ["ja": "離席中"],
        "Remove": ["ja": "削除"],
        "Max participants:": ["ja": "最大参加者数:"],
        "Language": ["ja": "言語"],

        // QR panel
        "Room Code": ["ja": "ルームコード"],
        "Scan or enter code to join": ["ja": "QRコードをスキャンまたはコードを入力して参加"],
        "Tap to copy link": ["ja": "タップしてリンクをコピー"],
        "Copied!": ["ja": "コピーしました！"],

        // Message row
        "Reply": ["ja": "返信"],
        "Save": ["ja": "保存"],
        "Cancel": ["ja": "キャンセル"],
        "Listening...": ["ja": "聞いています…"],
        "Recording...": ["ja": "録音中…"],
        "Send as": ["ja": "送信形式"],
        "Text": ["ja": "テキスト"],
        "Voice message": ["ja": "ボイスメッセージ"],
        "Send voice message": ["ja": "ボイスメッセージを送信"],
        "Show text": ["ja": "テキストを表示"],
        "Hide text": ["ja": "テキストを隠す"],
        "Play": ["ja": "再生"],
        "Pause": ["ja": "一時停止"],
        "Playback speed": ["ja": "再生速度"],
        "Voice message expired": ["ja": "ボイスメッセージの期限切れ"],
        "What's the Vibe?": ["ja": "バイブって？"],
        "A live party meter for the room. It climbs when people chat, and fastest when English and Japanese go back and forth.": ["ja": "部屋の盛り上がりメーター。チャットすると上がり、英語と日本語が交互に飛び交うと一番上がります。"],
        "Last minute": ["ja": "直近1分"],
        "Each message": ["ja": "メッセージ1件"],
        "EN ⇄ JA switch": ["ja": "英⇄日の切り替え"],
        "Back-and-forth combo": ["ja": "かけ合いコンボ"],
        "up to ×2": ["ja": "最大×2"],
        "Party mode is on!": ["ja": "パーティーモード中！"],
        "Party mode at 150: confetti for every new message": ["ja": "150でパーティーモード：新しいメッセージごとに紙吹雪"],
        "Only the last minute counts, so it cools off when the chat goes quiet.": ["ja": "直近1分だけをカウントするので、静かになると下がります。"],
        "Photo": ["ja": "写真"],
        "Drawing": ["ja": "お絵描き"],
        "Processing failed": ["ja": "処理に失敗しました"],

        // Status
        "online": ["ja": "オンライン"],
        "away": ["ja": "離席"],

        // Context menu
        "Copy": ["ja": "コピー"],
        "Delete": ["ja": "削除"],
        "Delete this message?": ["ja": "このメッセージを削除しますか？"],
        "This will remove the message for everyone.": ["ja": "全員のメッセージが削除されます。"],

        // System messages
        "has joined": ["ja": "が参加しました"],
        "has left": ["ja": "が退出しました"],

        // Language toggles
        "Romaji": ["ja": "ローマ字"],
        "Chat text size": ["ja": "文字サイズ"],
        "Small": ["ja": "小"],
        "Medium": ["ja": "中"],
        "Large": ["ja": "大"],

        // Typing indicator
        "is typing": ["ja": "が入力中"],
        "is drawing": ["ja": "が描画中"],
        "is speaking": ["ja": "が話し中"],
        "Drawing…": ["ja": "お絵描き中…"],
        "marked": ["ja": "マーク"],
        "Speaking…": ["ja": "話し中…"],

        // Game status bar
        "Guessing": ["ja": "推測中"],
        "Starting": ["ja": "開始中"],

        // Drawing composer
        "Clear": ["ja": "消去"],
        "Send": ["ja": "送信"],

        // Game
        "Game": ["ja": "ゲーム"],
        "Games": ["ja": "ゲーム"],
        "More tools": ["ja": "ツール"],
        "Only the host can start a game.": ["ja": "ゲームを開始できるのはホストだけです。"],
        "Got it": ["ja": "了解"],
        "Lost in Translation": ["ja": "ロスト・イン・トランスレーション"],
        "A drawing guessing game: one player draws, everyone else picks from 4 choices. 10 rounds, rotating drawer!": [
            "ja": "お絵描き当てゲーム：1人が描き、他の全員が4択から選ぶ。10ラウンド、描く人は交代！",
        ],
        "players": ["ja": "人のプレイヤー"],
        "Need at least 2 players to start.": ["ja": "開始するには2人以上のプレイヤーが必要です。"],
        "Start Game": ["ja": "ゲーム開始"],
        "Step": ["ja": "ステップ"],
        "of": ["ja": "/"],
        "Draw this phrase:": ["ja": "このフレーズを描いてください："],
        "What is this drawing?": ["ja": "この絵は何ですか？"],
        "Type your guess...": ["ja": "答えを入力…"],
        
        "Submit": ["ja": "送信"],
        "Game Results": ["ja": "ゲーム結果"],
        "Chain": ["ja": "チェーン"],
        "Original:": ["ja": "元の言葉："],
        "drew": ["ja": "が描いた"],
        "guessed": ["ja": "が当てた"],
        "Game complete! View Results": ["ja": "ゲーム完了！結果を見る"],
        "Game Started: Lost in Translation": ["ja": "ゲーム開始：ロスト・イン・トランスレーション"],
        "Game ended": ["ja": "ゲーム終了"],
        "End Game": ["ja": "ゲーム終了"],
        "Play Again": ["ja": "もう一回"],
        "Round Complete!": ["ja": "ラウンド完了！"],
        "turns played": ["ja": "ターンプレイ済み"],
        "Keep Playing": ["ja": "続ける"],
        "End game?": ["ja": "ゲームを終了しますか？"],
        "This will end the game for all players and show results.": ["ja": "全プレイヤーのゲームを終了し、結果を表示します。"],
        "Quit game?": ["ja": "ゲームをやめますか？"],
        "Are you sure you want to quit the game?": ["ja": "本当にゲームをやめますか？"],
        "Quit": ["ja": "やめる"],
        "Waiting for other players...": ["ja": "他のプレイヤーを待っています…"],
        "Close": ["ja": "閉じる"],
        "Minimize": ["ja": "最小化"],
        "Resume": ["ja": "再開"],
        "Resume Truth or Dare": ["ja": "真実か挑戦を再開"],
        "Resume Emoji Match": ["ja": "絵文字マッチを再開"],
        "Resume Emoji Bingo": ["ja": "絵文字ビンゴを再開"],
        "Roll!": ["ja": "ロール！"],
        "Your turn to roll!": ["ja": "あなたのロール番です！"],
        "is rolling...": ["ja": "がロール中…"],

        // Game levels
        "Level": ["ja": "レベル"],
        "Hint:": ["ja": "ヒント："],
        "Next Level": ["ja": "次のレベル"],
        "1 word with hint": ["ja": "1単語＋ヒント"],
        "2 words": ["ja": "2単語"],
        "words": ["ja": "単語"],

        // Dynamic game flow
        "Round": ["ja": "ラウンド"],
        "guessed correctly!": ["ja": "正解！"],
        "guessed wrong": ["ja": "不正解"],

        // Multiple-choice game
        "Correct!": ["ja": "正解!"],
        "Wrong!": ["ja": "不正解!"],
        "Scores": ["ja": "スコア"],
        "picked": ["ja": "を選んだ"],
        "10 rounds": ["ja": "10ラウンド"],
        "correct": ["ja": "正解"],

        // Emojifyr leftovers (shared strings)
        "Random": ["ja": "ランダム"],
        "I don't know": ["ja": "わからない"],
        "Use": ["ja": "使う"],
        "Regenerate": ["ja": "再生成"],
        "What does this mean?": ["ja": "これはどういう意味？"],
        "What is this phrase?": ["ja": "このフレーズの意味は？"],
        "Submit Guess": ["ja": "回答する"],
        "Original": ["ja": "元の言葉"],
        "Guesses:": ["ja": "回答："],
        "Continue": ["ja": "続ける"],
        "Game Started: Match Emoji": ["ja": "ゲーム開始：マッチ絵文字"],
        "Game Started: Emoji Bingo": ["ja": "ゲーム開始：絵文字ビンゴ"],
        "Can't play this clip": ["ja": "この音声は再生できません"],
        "Game ended early": ["ja": "ゲーム途中終了"],
        "Game Complete": ["ja": "ゲーム完了"],
        "pair": ["ja": "ペア"],
        "pairs": ["ja": "ペア"],
        "played": ["ja": "プレイ"],
        "Reveal": ["ja": "答えを見る"],
        "Next Round": ["ja": "次のラウンド"],
        "Off": ["ja": "オフ"],
        "Reveal Answers": ["ja": "答えを公開"],
        "Guess submitted!": ["ja": "回答送信済み！"],
        "Waiting for reveal...": ["ja": "公開を待っています…"],
        "guess": ["ja": "回答"],
        "guesses": ["ja": "回答"],
        "Waiting for": ["ja": "待っています"],
        "Someone": ["ja": "誰か"],
        "Game Starting...": ["ja": "ゲーム開始中…"],

        // Word Rush
        "Resume Word Rush": ["ja": "ワードラッシュを再開"],
        "Game Started: Word Rush": ["ja": "ゲーム開始：ワードラッシュ"],
        "Guess the word from 3 emoji. Learn it. Say it!": ["ja": "3つの絵文字から単語を当てて、覚えて、言ってみよう！"],
        "Word pack": ["ja": "単語パック"],
        "Mix": ["ja": "ミックス"],
        "Foodie": ["ja": "グルメ"],
        "Travel": ["ja": "旅行"],
        "Slang": ["ja": "スラング"],
        "Anime": ["ja": "アニメ"],
        "Feelings": ["ja": "気持ち"],
        "From this chat": ["ja": "このチャットから"],
        "Every 2nd word, someone takes the mic": ["ja": "2問ごとに誰かがマイクで発音チャレンジ"],
        "Say it! needs 2+ players": ["ja": "言ってみよう！は2人以上で"],
        "AI cards cooking…": ["ja": "AIカードを準備中…"],
        "Fresh AI cards ready!": ["ja": "新しいAIカードの準備OK！"],
        "Dealing fresh cards…": ["ja": "新しいカードを配っています…"],
        "learning": ["ja": "学習中"],
        "you": ["ja": "あなた"],
        "JOIN!": ["ja": "参加する！"],
        "Not now": ["ja": "あとで"],
        "Leave": ["ja": "抜ける"],
        "START WORD RUSH!": ["ja": "ワードラッシュ開始！"],
        "Waiting for the host to start…": ["ja": "ホストの開始を待っています…"],
        "Skip ahead": ["ja": "次へスキップ"],
        "End game": ["ja": "ゲーム終了"],
        "End Word Rush for everyone?": ["ja": "全員のワードラッシュを終了しますか？"],
        "faster = more points": ["ja": "早いほど高得点"],
        "What's this in English?": ["ja": "この絵文字、なんて英語？"],
        "What's this in Japanese?": ["ja": "この絵文字、日本語で何？"],
        "Hint": ["ja": "ヒント"],
        "{n} in a row": ["ja": "{n}連続"],
        "LOCKED IN!": ["ja": "決定！"],
        "{a}/{b} in": ["ja": "{a}/{b}人 回答"],
        "One more emoji might give it away…!": ["ja": "あと1つで答えが見えるかも…！"],
        "All 3 are out — go go go!": ["ja": "3つ揃った！いそげ〜！"],
        "Locked in! Waiting for the others…": ["ja": "決定！みんなを待ってるよ…"],
        "You're watching this round": ["ja": "観戦中だよ"],
        "GOT IT!": ["ja": "正解！"],
        "MISS…": ["ja": "ざんねん…"],
        "miss": ["ja": "ミス"],
        "SAY IT! IS NEXT": ["ja": "次は「言ってみよう！」"],
        "Next word in {n}s": ["ja": "あと{n}秒で次の単語"],
        "NEXT WORD ➜": ["ja": "次の単語 ➜"],
        "YOUR TURN ON THE MIC!": ["ja": "あなたがマイクの番！"],
        "ON THE MIC!": ["ja": "ON THE MIC!"],
        "Tap to record (5s max)": ["ja": "タップで録音（最大5秒）"],
        "● REC {t} · tap to stop": ["ja": "● REC {t} · タップで停止"],
        "Your take": ["ja": "あなたの録音"],
        "Retake": ["ja": "撮り直す"],
        "SEND!": ["ja": "送信！"],
        "Sending…": ["ja": "送信中…"],
        "Mic access is blocked. Allow the microphone in Settings, or skip this one.": ["ja": "マイクがオフになっています。設定でマイクを許可するか、今回はスキップしてね。"],
        "Judges": ["ja": "審査員"],
        "English natives' votes count ×2": ["ja": "英語ネイティブの票は2倍"],
        "Japanese natives' votes count ×2": ["ja": "日本語ネイティブの票は2倍"],
        "NATIVE ×2": ["ja": "ネイティブ×2"],
        "×2 NATIVE JUDGE": ["ja": "×2 ネイティブ審査員"],
        "Record": ["ja": "録音"],
        "Stop": ["ja": "停止"],
        "{name}'s on the mic!": ["ja": "{name}さんがマイクの番！"],
        "Get your judging thumbs ready…": ["ja": "審査の準備をしてね…"],
        "{name} said it!": ["ja": "{name}さんが言った！"],
        "How did {name} do?": ["ja": "{name}さんの発音はどうだった？"],
        "Huh?": ["ja": "え？"],
        "try again!": ["ja": "もう一回！"],
        "Close!": ["ja": "おしい！"],
        "almost there": ["ja": "あと少し"],
        "Native!": ["ja": "ネイティブ！"],
        "nailed it": ["ja": "完璧！"],
        "Teach {name}": ["ja": "{name}さんにお手本"],
        "record how you say it": ["ja": "あなたの発音を録音"],
        "Sent! They'll hear your version": ["ja": "送信しました！お手本が届きます"],
        "{name} already taught this one": ["ja": "{name}さんがもうお手本を送りました"],
        "The room is judging…": ["ja": "みんなが審査中…"],
        "{a}/{b} voted": ["ja": "{a}/{b}人 投票"],
        "No clip came through": ["ja": "録音が届きませんでした"],
        "NATIVE!": ["ja": "ネイティブ級！"],
        "CLOSE!": ["ja": "おしい！！"],
        "HUH?": ["ja": "え？？"],
        "+{n} BONUS": ["ja": "+{n} ボーナス"],
        "Nobody voted this time": ["ja": "今回は投票なし"],
        "{name}'s version": ["ja": "{name}さんのお手本"],
        "BRAIN JUICE!!": ["ja": "脳汁ドバドバ!!"],
        "streak": ["ja": "連続"],
        "say it": ["ja": "発音"],
        "BACK TO CHAT": ["ja": "チャットに戻る"],
        "AGAIN!": ["ja": "もう一回！"],
        "pts": ["ja": "点"],

        // Truth or Dare
        "Truth or Dare": ["ja": "どっちする？"],
        "Game Started: Truth or Dare": ["ja": "ゲーム開始：どっちする？"],
        "Truth or Dare?": ["ja": "どっちする？"],
        "Truth": ["ja": "ほんとのこと"],
        "Dare": ["ja": "チャレンジ"],
        "A social game: answer a question or complete a challenge! Take turns with your group.": [
            "ja": "みんなで順番に質問に答えたり、チャレンジしたりするゲームです！",
        ],
        "It's your turn!": ["ja": "あなたの番です！"],
        "'s turn!": ["ja": "さんの番です！"],
        "to choose...": ["ja": "が選んでいます…"],
        "to respond...": ["ja": "が答えています…"],
        "Skip": ["ja": "スキップ"],
        "Next Turn": ["ja": "次の人へ"],
        "Type your answer...": ["ja": "答えを入力…"],
        "Take a photo": ["ja": "写真を撮る"],
        "Draw your answer": ["ja": "絵で答える"],
        "Send Answer": ["ja": "答えを送信"],
        "Skipped!": ["ja": "スキップしました！"],
        "answered:": ["ja": "の答え："],
        "Rotates through all players": ["ja": "全員が順番にプレイ"],
        "Waiting for host...": ["ja": "ホストを待っています…"],
        "Rate this answer": ["ja": "この答えを評価"],
        "Ratings": ["ja": "評価"],
        "Submit Rating": ["ja": "評価を送信"],
        "Waiting for others to rate...": ["ja": "他の人の評価を待っています…"],
        "Skip ratings": ["ja": "評価をスキップ"],
        "Done Dare": ["ja": "チャレンジ完了"],
        "Normal": ["ja": "ノーマル"],
        "Deep": ["ja": "ディープ"],

        // Host room + conversation (pop restyle)
        "Pick your look, then I'll make you a QR code!": ["ja": "見た目を選んでね、QRコードを作るよ！"],
        "Room Ready!": ["ja": "ルーム準備完了！"],
        "joined!": ["ja": "人参加！"],
        "Open Conversation": ["ja": "会話を開く"],
        "Share Link": ["ja": "リンクを共有"],
        "React": ["ja": "リアクション"],
        "You're offline": ["ja": "オフラインです"],
        "queued": ["ja": "件待機中"],
        "Download Offline Translation": ["ja": "オフライン翻訳をダウンロード"],
        "Enables translation without internet": ["ja": "インターネットなしで翻訳できます"],
        "Offline translation ready": ["ja": "オフライン翻訳の準備完了"],

        // Game picker + party games (pop restyle)
        "Pick a game!": ["ja": "ゲームをえらぼう！"],
        "Word Rush": ["ja": "ワードラッシュ"],
        "Emoji Bingo": ["ja": "絵文字ビンゴ"],
        "Emoji Match": ["ja": "絵文字マッチ"],
        "Emoji drop in — race to pick the word!": ["ja": "絵文字が落ちてくる — 早押しで単語をえらべ！"],
        "draw & guess": ["ja": "描いて当てる"],
        "roll & stamp": ["ja": "振ってスタンプ"],
        "flip the pairs": ["ja": "ペアをめくろう"],
        "brave or honest?": ["ja": "勇気か、正直か？"],
        "Pack": ["ja": "パック"],
        "Timer": ["ja": "タイマー"],
        "Say it!": ["ja": "言ってみよう！"],
        "Every 2nd card, one player says the word out loud — everyone else judges! Native speakers count double.": [
            "ja": "2枚ごとに1人が単語を声に出して言う — みんなでジャッジ！ネイティブの票は2倍。",
        ],
        "Works both ways: English speakers learn Japanese (with romaji), Japanese speakers learn English.": [
            "ja": "どっちも学べる：英語の人は日本語（ローマ字つき）、日本語の人は英語を練習！",
        ],
        "Start Word Rush!": ["ja": "ワードラッシュ開始！"],
        "Start Bingo!": ["ja": "ビンゴ開始！"],
        "Start Match!": ["ja": "マッチ開始！"],
        "Start Truth or Dare!": ["ja": "どっちする？開始！"],
        "Mark emojis on your card as they're called. First to complete the pattern wins!": [
            "ja": "呼ばれた絵文字をカードにスタンプ。最初にそろえた人の勝ち！",
        ],
        "Find matching emoji pairs! Take turns flipping cards.": ["ja": "同じ絵文字のペアを探そう！順番にカードをめくってね。"],
        "Works solo or multiplayer": ["ja": "ひとりでもみんなでも遊べる"],
        "Match emojis on your card as they are called!": ["ja": "呼ばれた絵文字をカードでさがそう！"],
        "You": ["ja": "あなた"],
        "HOST": ["ja": "ホスト"],
        "Players": ["ja": "プレイヤー"],
        "Win Pattern:": ["ja": "勝ちパターン："],
        "Line": ["ja": "1列"],
        "Four Corners": ["ja": "4すみ"],
        "Blackout": ["ja": "ぜんぶ"],
        "called": ["ja": "コール済み"],
        "BINGO!": ["ja": "ビンゴ！"],
        "1 AWAY!": ["ja": "あと1つ！"],
        "finished": ["ja": "人あがり"],
        "Waiting for your card...": ["ja": "カードを待っています…"],
        "emojis called": ["ja": "個コール"],
        "You Won!": ["ja": "あなたの勝ち！"],
        "Won!": ["ja": "の勝ち！"],
        "Game Over": ["ja": "ゲームオーバー"],
        "Back to Chat": ["ja": "チャットにもどる"],
        "Again!": ["ja": "もう一回！"],
        "Join Game": ["ja": "参加する"],
        "Leave Lobby": ["ja": "ロビーを出る"],
        "Your turn!": ["ja": "あなたの番！"],
        "Find a pair": ["ja": "ペアをさがせ"],
        "'s turn": ["ja": "の番"],
        "turns": ["ja": "ターン"],
        "PAIR!": ["ja": "ペア！"],
        "COMBO": ["ja": "コンボ"],
        "Board Cleared!": ["ja": "ぜんぶクリア！"],
        "It's a Tie!": ["ja": "引き分け！"],
        "Game Canceled": ["ja": "ゲーム中止"],
        "Everyone rates your answer 1–5": ["ja": "みんながあなたの答えを1〜5で評価"],
        "Last turn": ["ja": "前のターン"],
        "rated": ["ja": "評価済み"],
    ]

    /// Translate a UI string. Returns the key unchanged for English or missing translations.
    static func t(_ key: String, _ lang: String) -> String {
        if lang == "en" { return key }
        return translations[key]?[lang] ?? key
    }
}
